import {
  BUILT_INS_LIBRARY_ID,
  type BuiltInTemplate,
  TEMPLATE_CATALOG_VERSION,
  type TemplateCategory,
  type TemplateDefinition,
  type TemplateKind,
} from "./types"

const input = (name: string, description: string, required = false) => ({
  name,
  description,
  required,
})

const ARTIFACT_TEMPLATE_DEFINITIONS: TemplateDefinition[] = [
  {
    id: "narrative-pitch",
    kind: "artifact",
    category: "Deck",
    format: "html",
    title: "Narrative pitch",
    defaultTitle: "Narrative pitch",
    description: "A spoken story that moves from a changing world to proof and a clear plan.",
    outcome: "Win belief before asking for action.",
    sections: ["The change", "The tension", "The insight", "The product", "The proof", "The plan"],
    inputs: [
      input("Audience", "Who needs to believe this?", true),
      input("Objective", "What should they do next?", true),
      input("Evidence", "Artifacts or facts that support the story"),
    ],
    tags: ["pitch", "story", "deck"],
    featured: true,
  },
  {
    id: "seed-fundraising",
    kind: "artifact",
    category: "Deck",
    format: "html",
    title: "Seed fundraising",
    defaultTitle: "Seed round",
    description:
      "A founder-led seed narrative with a sharp wedge, credible momentum, and a precise ask.",
    outcome: "Make the opportunity legible without sanding off the founder's point of view.",
    sections: ["Why now", "The wedge", "Product", "Market", "Traction", "Model", "Team", "The ask"],
    inputs: [
      input("Company", "Company or project name", true),
      input("Round", "Target raise and use of funds"),
      input("Traction", "The evidence that deserves the room"),
    ],
    tags: ["fundraising", "founder", "deck"],
  },
  {
    id: "product-launch",
    kind: "artifact",
    category: "Deck",
    format: "html",
    title: "Product launch",
    defaultTitle: "Product launch",
    description:
      "A reveal built around the audience's tension, the new capability, and the moment to act.",
    outcome: "Turn a feature announcement into a memorable change in the user's world.",
    sections: [
      "Audience",
      "Before",
      "Reveal",
      "How it works",
      "Why it matters",
      "Proof",
      "Availability",
    ],
    inputs: [
      input("Product", "What is launching?", true),
      input("Audience", "Who feels the change first?", true),
      input("Proof", "Demo, quote, or measurable result"),
    ],
    tags: ["launch", "marketing", "deck"],
  },
  {
    id: "quarterly-business-review",
    kind: "artifact",
    category: "Deck",
    format: "html",
    title: "Quarterly business review",
    defaultTitle: "Quarterly business review",
    description:
      "A decision-oriented review of goals, drivers, evidence, risks, and next-quarter commitments.",
    outcome: "Leave the room with shared signal and named commitments.",
    sections: [
      "Quarter in one page",
      "Scorecard",
      "Drivers",
      "Customers",
      "Risks",
      "Decisions",
      "Commitments",
    ],
    inputs: [
      input("Period", "Quarter or review window", true),
      input("Metrics", "The source of truth for the scorecard", true),
      input("Decisions", "Items that need a call"),
    ],
    tags: ["qbr", "operations", "deck"],
    featured: true,
  },
  {
    id: "research-briefing",
    kind: "artifact",
    category: "Deck",
    format: "html",
    title: "Research briefing",
    defaultTitle: "Research briefing",
    description:
      "Question, evidence, interpretation, uncertainty, and recommendation in a reviewable arc.",
    outcome: "Help a busy audience understand what the evidence changes.",
    sections: [
      "Question",
      "Method",
      "Signal",
      "Evidence",
      "Interpretation",
      "Uncertainty",
      "Recommendation",
    ],
    inputs: [
      input("Question", "The question this research answers", true),
      input("Sources", "Research artifacts or datasets", true),
      input("Audience", "Who will act on the answer?"),
    ],
    tags: ["research", "evidence", "deck"],
  },
  {
    id: "board-update",
    kind: "artifact",
    category: "Deck",
    format: "html",
    title: "Board update",
    defaultTitle: "Board update",
    description:
      "Executive signal first: progress, financial view, strategic risk, asks, and appendix.",
    outcome: "Use board time for judgment rather than narration.",
    sections: [
      "Executive signal",
      "Progress",
      "Financial view",
      "Strategy",
      "Risks",
      "Board asks",
      "Appendix",
    ],
    inputs: [
      input("Period", "Reporting period", true),
      input("Plan", "The goals being measured against"),
      input("Asks", "Where the board can help"),
    ],
    tags: ["board", "executive", "deck"],
  },
  {
    id: "decision-memo",
    kind: "artifact",
    category: "Doc",
    format: "md",
    title: "Decision memo",
    defaultTitle: "Decision memo",
    description:
      "A durable record of the call, the alternatives, the rationale, and the revisit trigger.",
    outcome: "Make a consequential choice easy to review now and understand later.",
    sections: [
      "Decision",
      "Context",
      "Options considered",
      "Rationale",
      "Consequences",
      "Owners",
      "Revisit trigger",
    ],
    inputs: [
      input("Decision", "The choice being made", true),
      input("Owner", "Who is accountable?", true),
      input("Evidence", "Artifacts that support the choice"),
    ],
    tags: ["decision", "leadership", "doc"],
    featured: true,
  },
  {
    id: "product-brief",
    kind: "artifact",
    category: "Doc",
    format: "md",
    title: "Product brief",
    defaultTitle: "Product brief",
    description: "Problem, users, principles, flows, scope, requirements, risks, and measures.",
    outcome: "Give design and engineering enough shared truth to make good local decisions.",
    sections: [
      "Problem",
      "Users",
      "Principles",
      "Experience",
      "Scope",
      "Requirements",
      "Risks",
      "Measures",
      "Open questions",
    ],
    inputs: [
      input("Problem", "What is failing today?", true),
      input("Users", "Who experiences it?", true),
      input("Evidence", "Research and product artifacts"),
    ],
    tags: ["product", "brief", "doc"],
  },
  {
    id: "technical-design",
    kind: "artifact",
    category: "Doc",
    format: "md",
    title: "Technical design",
    defaultTitle: "Technical design",
    description:
      "System context, constraints, proposal, data model, failure modes, migration, and alternatives.",
    outcome: "Create a technical record that survives the implementation.",
    sections: [
      "Summary",
      "System context",
      "Constraints",
      "Proposal",
      "Data model",
      "Interfaces",
      "Failure modes",
      "Migration",
      "Observability",
      "Alternatives",
    ],
    inputs: [
      input("System", "The capability or boundary changing", true),
      input("Constraints", "Hard requirements and limits"),
      input("References", "Relevant code or architecture artifacts"),
    ],
    tags: ["engineering", "architecture", "doc"],
  },
  {
    id: "strategy-narrative",
    kind: "artifact",
    category: "Doc",
    format: "md",
    title: "Strategy narrative",
    defaultTitle: "Strategy narrative",
    description: "A diagnosis, an explicit choice, and coherent actions—not a list of ambitions.",
    outcome: "Make the tradeoff at the heart of the strategy impossible to miss.",
    sections: [
      "Current reality",
      "Diagnosis",
      "Choice",
      "Coherent actions",
      "Capabilities",
      "Sequence",
      "Non-goals",
    ],
    inputs: [
      input("Arena", "Where the strategy applies", true),
      input("Evidence", "What makes the diagnosis credible"),
      input("Constraints", "What cannot be wished away"),
    ],
    tags: ["strategy", "leadership", "doc"],
  },
  {
    id: "launch-plan",
    kind: "artifact",
    category: "Doc",
    format: "md",
    title: "Launch plan",
    defaultTitle: "Launch plan",
    description:
      "Audience, position, channels, assets, milestones, owners, dependencies, and rollback.",
    outcome: "Coordinate a launch without turning the plan into a task dump.",
    sections: [
      "Outcome",
      "Audience",
      "Positioning",
      "Channels",
      "Assets",
      "Milestones",
      "Owners",
      "Dependencies",
      "Rollback",
    ],
    inputs: [
      input("Launch", "What is going live?", true),
      input("Date", "Target window"),
      input("Owners", "Teams or individuals accountable"),
    ],
    tags: ["launch", "program", "doc"],
  },
  {
    id: "postmortem",
    kind: "artifact",
    category: "Doc",
    format: "md",
    title: "Postmortem",
    defaultTitle: "Postmortem",
    description:
      "Impact, timeline, contributing conditions, response, learning, and verified corrective action.",
    outcome: "Learn without blame and close the loop on corrective work.",
    sections: [
      "Summary",
      "Impact",
      "Timeline",
      "Contributing conditions",
      "Response",
      "What worked",
      "What changes",
      "Verification",
    ],
    inputs: [
      input("Incident", "What happened?", true),
      input("Window", "Incident start and recovery"),
      input("Evidence", "Logs, messages, or related artifacts"),
    ],
    tags: ["incident", "learning", "doc"],
  },
  {
    id: "meeting-synthesis",
    kind: "artifact",
    category: "Doc",
    format: "md",
    title: "Meeting synthesis",
    defaultTitle: "Meeting synthesis",
    description:
      "Signal, decisions, disagreements, actions, and unresolved questions—without transcript theater.",
    outcome: "Turn a meeting into a compact piece of shared memory.",
    sections: [
      "Purpose",
      "Participants",
      "Signal",
      "Decisions",
      "Disagreements",
      "Actions",
      "Open questions",
    ],
    inputs: [
      input("Notes", "Transcript or raw notes", true),
      input("Purpose", "Why the meeting happened"),
      input("Audience", "Who needs the synthesis"),
    ],
    tags: ["meeting", "notes", "doc"],
  },
  {
    id: "research-plan",
    kind: "artifact",
    category: "Doc",
    format: "md",
    title: "Research plan",
    defaultTitle: "Research plan",
    description:
      "Question, hypotheses, sources, method, analysis, ethics, schedule, and output contract.",
    outcome: "Align on how evidence will be gathered before the first interview or query.",
    sections: [
      "Question",
      "Hypotheses",
      "Participants or sources",
      "Method",
      "Analysis plan",
      "Ethics",
      "Schedule",
      "Outputs",
    ],
    inputs: [
      input("Question", "What must the work answer?", true),
      input("Decision", "What will the answer inform?"),
      input("Constraints", "Time, access, or ethical limits"),
    ],
    tags: ["research", "planning", "doc"],
  },
  {
    id: "weekly-operating-review",
    kind: "artifact",
    category: "Report",
    format: "md",
    title: "Weekly operating review",
    defaultTitle: "Weekly operating review",
    description:
      "What changed, leading indicators, blockers, decisions, commitments, and owner follow-through.",
    outcome: "Run the week from deltas and decisions, not status narration.",
    sections: [
      "Week in one line",
      "What changed",
      "Leading indicators",
      "Blockers",
      "Decisions",
      "Commitments",
      "Carry-over",
    ],
    inputs: [
      input("Week", "Reporting week", true),
      input("Metrics", "Current operating signal"),
      input("Prior review", "Last week's commitments"),
    ],
    tags: ["weekly", "operations", "report"],
  },
  {
    id: "customer-health-report",
    kind: "artifact",
    category: "Report",
    format: "md",
    title: "Customer health report",
    defaultTitle: "Customer health report",
    description: "Outcomes, usage, stakeholder map, risks, opportunities, and mutual commitments.",
    outcome: "See the account as a relationship and outcome system, not a health score.",
    sections: [
      "Executive read",
      "Outcomes",
      "Usage",
      "Stakeholders",
      "Risks",
      "Opportunities",
      "Commitments",
    ],
    inputs: [
      input("Account", "Customer or partner", true),
      input("Evidence", "Notes, usage, and commitments", true),
      input("Period", "Review window"),
    ],
    tags: ["customer", "account", "report"],
  },
  {
    id: "market-landscape",
    kind: "artifact",
    category: "Report",
    format: "md",
    title: "Market landscape",
    defaultTitle: "Market landscape",
    description:
      "Category definition, forces, segments, players, comparison method, whitespace, and implications.",
    outcome: "Replace logo maps with a defensible view of how a market is moving.",
    sections: [
      "Category",
      "Forces",
      "Segments",
      "Players",
      "Comparison",
      "Whitespace",
      "Implications",
      "Sources",
    ],
    inputs: [
      input("Market", "The category being studied", true),
      input("Question", "What decision should this inform?"),
      input("Sources", "Research artifacts or links"),
    ],
    tags: ["market", "competitive", "report"],
  },
  {
    id: "project-hub",
    kind: "artifact",
    category: "Site",
    format: "html",
    title: "Project hub",
    defaultTitle: "Project hub",
    description:
      "A living front door for the brief, status, milestones, decisions, artifacts, and people.",
    outcome: "Give a project one understandable home without replacing its working tools.",
    sections: ["Brief", "Now", "Milestones", "Decisions", "Artifacts", "People", "Update history"],
    inputs: [
      input("Project", "Project name", true),
      input("Outcome", "What success changes"),
      input("Artifacts", "The work this hub should point to"),
    ],
    tags: ["project", "hub", "site"],
  },
  {
    id: "launch-page",
    kind: "artifact",
    category: "Site",
    format: "html",
    title: "Launch page",
    defaultTitle: "Launch page",
    description:
      "A focused single-page story with value, proof, product explanation, detail, and action.",
    outcome: "Make the value obvious before asking the visitor to understand the machinery.",
    sections: ["Value proposition", "Proof", "How it works", "Use cases", "Details", "Action"],
    inputs: [
      input("Offer", "What is available?", true),
      input("Audience", "Who should care?", true),
      input("Proof", "Evidence, quote, or result"),
    ],
    tags: ["launch", "marketing", "site"],
  },
  {
    id: "context-manifest",
    kind: "artifact",
    category: "Agent",
    format: "md",
    title: "Context manifest",
    defaultTitle: "Context manifest",
    description:
      "Purpose, sources, operating rules, tool expectations, publish behavior, and starter prompts.",
    outcome: "Make an agent setup understandable before it acts.",
    sections: [
      "Purpose",
      "What this context knows",
      "Operating rules",
      "Tools",
      "Publishing",
      "Boundaries",
      "Starter prompts",
    ],
    inputs: [
      input("Job", "What should this context make easier?", true),
      input("Sources", "What should it know?"),
      input("Boundaries", "What must it not do?"),
    ],
    tags: ["context", "agent", "manifest"],
  },
  {
    id: "skill-package",
    kind: "artifact",
    category: "Agent",
    format: "md",
    title: "Skill package",
    defaultTitle: "Skill package",
    description:
      "Trigger, inputs, procedure, safety boundaries, output contract, examples, and verification.",
    outcome: "Turn expert practice into a procedure an agent can use reliably.",
    sections: [
      "When to use",
      "Inputs",
      "Procedure",
      "Safety",
      "Output contract",
      "Examples",
      "Verification",
    ],
    inputs: [
      input("Capability", "What should the skill enable?", true),
      input("Triggers", "When should an agent reach for it?"),
      input("Examples", "Representative successful cases"),
    ],
    tags: ["skill", "agent", "procedure"],
  },
  {
    id: "review-rubric",
    kind: "artifact",
    category: "Agent",
    format: "md",
    title: "Review rubric",
    defaultTitle: "Review rubric",
    description:
      "Criteria, severity, evidence requirements, pass conditions, and a concise response format.",
    outcome: "Make automated and human review consistent without hiding judgment.",
    sections: [
      "Purpose",
      "Criteria",
      "Severity",
      "Evidence",
      "Pass conditions",
      "Response format",
      "Examples",
    ],
    inputs: [
      input("Subject", "What is being reviewed?", true),
      input("Standards", "Policies or examples to apply"),
      input("Audience", "Who receives the findings?"),
    ],
    tags: ["review", "quality", "agent"],
  },
  {
    id: "automation-brief",
    kind: "artifact",
    category: "Agent",
    format: "md",
    title: "Automation brief",
    defaultTitle: "Automation brief",
    description:
      "Trigger, instruction, sources, expected outputs, failure handling, approvals, and observability.",
    outcome: "Specify recurring agent work so its behavior can be reviewed before it runs.",
    sections: [
      "Outcome",
      "Trigger",
      "Instruction",
      "Sources",
      "Output",
      "Approvals",
      "Failure handling",
      "Observability",
    ],
    inputs: [
      input("Job", "What repeats?", true),
      input("Trigger", "When should it run?", true),
      input("Authority", "What may it publish or change?"),
    ],
    tags: ["automation", "agent", "operations"],
  },
  {
    id: "source-guide",
    kind: "artifact",
    category: "Agent",
    format: "md",
    title: "Source guide",
    defaultTitle: "Source guide",
    description:
      "What a connected system contains, preferred tools, query patterns, caveats, and citation rules.",
    outcome: "Help an agent use a source accurately without relearning its edges each session.",
    sections: [
      "Source",
      "What it contains",
      "Preferred tools",
      "Query patterns",
      "Caveats",
      "Citation rules",
      "Examples",
    ],
    inputs: [
      input("System", "The connected source", true),
      input("Tools", "Available operations"),
      input("Caveats", "Known gaps or permission boundaries"),
    ],
    tags: ["source", "agent", "guide"],
  },
]

const CONTEXT_TEMPLATE_DEFINITIONS: TemplateDefinition[] = [
  {
    id: "weekly-research-context",
    kind: "context",
    category: "Agent",
    format: "md",
    title: "Weekly research brief",
    defaultTitle: "Weekly research brief manifest",
    description:
      "Tracks a topic, reads approved sources, and proposes a cited weekly digest for review.",
    outcome: "Stay current on a changing question without rebuilding the research loop each week.",
    sections: [
      "Purpose",
      "Approved sources",
      "Weekly procedure",
      "Evidence rules",
      "Output",
      "Review policy",
      "Boundaries",
    ],
    inputs: [
      input("Topic", "The question or market to track", true),
      input("Sources", "Approved artifacts, tags, or connections", true),
      input("Cadence", "When the brief should be ready"),
    ],
    tags: ["research", "weekly", "context"],
    featured: true,
    starterPrompts: [
      "What changed this week?",
      "Show the evidence behind the top signal.",
      "Draft this week's research brief.",
    ],
  },
  {
    id: "product-decision-context",
    kind: "context",
    category: "Agent",
    format: "md",
    title: "Product decision partner",
    defaultTitle: "Product decision partner manifest",
    description:
      "Loads strategy and user evidence, pressure-tests options, and proposes durable decision memos.",
    outcome: "Keep product judgment connected to evidence and prior choices.",
    sections: [
      "Purpose",
      "Strategy sources",
      "Evidence",
      "Decision method",
      "Output",
      "Review behavior",
      "Boundaries",
    ],
    inputs: [
      input("Strategy", "The strategy artifacts to hold constant", true),
      input("Evidence", "Research and product sources"),
      input("Authority", "Proposal-only or publish"),
    ],
    tags: ["product", "decision", "context"],
    starterPrompts: [
      "Pressure-test these options.",
      "What prior decisions constrain this?",
      "Propose a decision memo.",
    ],
  },
  {
    id: "customer-room-context",
    kind: "context",
    category: "Agent",
    format: "md",
    title: "Customer account room",
    defaultTitle: "Customer account room manifest",
    description:
      "Combines notes, usage, stakeholders, and commitments into a conservative living account view.",
    outcome: "Give the account team shared memory without flattening sensitive context.",
    sections: [
      "Purpose",
      "Account sources",
      "Stakeholder handling",
      "Health method",
      "Outputs",
      "Access",
      "Boundaries",
    ],
    inputs: [
      input("Account", "Customer or partner", true),
      input("Sources", "Notes, usage, and commitments", true),
      input("Sensitivity", "Special access constraints"),
    ],
    tags: ["customer", "account", "context"],
    starterPrompts: [
      "What changed in this account?",
      "Where are commitments at risk?",
      "Draft the next account review.",
    ],
  },
  {
    id: "launch-steward-context",
    kind: "context",
    category: "Agent",
    format: "md",
    title: "Launch steward",
    defaultTitle: "Launch steward manifest",
    description:
      "Tracks launch artifacts and milestones, catches drift, and proposes a weekly status revision.",
    outcome: "Keep a cross-functional launch coherent as the facts move.",
    sections: [
      "Purpose",
      "Launch sources",
      "Checks",
      "Update cadence",
      "Escalation",
      "Output",
      "Boundaries",
    ],
    inputs: [
      input("Launch", "The launch being stewarded", true),
      input("Plan", "The canonical launch plan", true),
      input("Signals", "Artifacts or systems that show progress"),
    ],
    tags: ["launch", "program", "context"],
    starterPrompts: [
      "What drifted since the last update?",
      "Which milestone is least credible?",
      "Propose this week's launch status.",
    ],
  },
  {
    id: "repository-guide-context",
    kind: "context",
    category: "Agent",
    format: "md",
    title: "Repository guide",
    defaultTitle: "Repository guide manifest",
    description:
      "Packages architecture, contribution rules, and review expectations for coding agents.",
    outcome: "Let coding agents begin with the repository's actual operating rules.",
    sections: [
      "Purpose",
      "Repository map",
      "Architecture",
      "Working rules",
      "Verification",
      "Review",
      "Boundaries",
    ],
    inputs: [
      input("Repository", "The codebase this context supports", true),
      input("Rules", "Contribution and verification artifacts"),
      input("Sources", "Architecture and product references"),
    ],
    tags: ["engineering", "repository", "context"],
    starterPrompts: [
      "Orient me to this repository.",
      "Which checks govern this change?",
      "Review this plan against the architecture.",
    ],
  },
  {
    id: "brand-guardian-context",
    kind: "context",
    category: "Agent",
    format: "md",
    title: "Brand guardian",
    defaultTitle: "Brand guardian manifest",
    description:
      "Loads Brandprint and approved assets, reviews outputs, and proposes a compatible visual direction.",
    outcome: "Make brand guidance useful at creation time without turning it into a gatekeeper.",
    sections: [
      "Purpose",
      "Brandprint",
      "Approved assets",
      "Review method",
      "Visual direction",
      "Output",
      "Boundaries",
    ],
    inputs: [
      input("Brandprint", "The workspace's brand profile", true),
      input("Assets", "Approved logos, imagery, or examples"),
      input("Strictness", "Advisory or approval-required"),
    ],
    tags: ["brand", "review", "context"],
    starterPrompts: [
      "Review this against our Brandprint.",
      "Propose a visual direction for this artifact.",
      "What is off-brand, and why?",
    ],
  },
]

const builtIn = (template: TemplateDefinition): BuiltInTemplate => ({
  ...template,
  libraryId: BUILT_INS_LIBRARY_ID,
  catalogVersion: TEMPLATE_CATALOG_VERSION,
})

export const ARTIFACT_TEMPLATES = ARTIFACT_TEMPLATE_DEFINITIONS.map(builtIn)
export const CONTEXT_TEMPLATES = CONTEXT_TEMPLATE_DEFINITIONS.map(builtIn)
export const BUILT_IN_TEMPLATES = [...ARTIFACT_TEMPLATES, ...CONTEXT_TEMPLATES]

export const TEMPLATE_CATEGORIES: readonly TemplateCategory[] = [
  "Deck",
  "Doc",
  "Report",
  "Site",
  "Agent",
]

export function listTemplates(filter?: {
  kind?: TemplateKind
  category?: TemplateCategory
  query?: string
}): readonly BuiltInTemplate[] {
  const needle = filter?.query?.trim().toLowerCase() ?? ""
  return BUILT_IN_TEMPLATES.filter((template) => {
    if (filter?.kind && template.kind !== filter.kind) return false
    if (filter?.category && template.category !== filter.category) return false
    if (!needle) return true
    return [
      template.title,
      template.description,
      template.outcome,
      template.category,
      ...template.tags,
    ]
      .join(" ")
      .toLowerCase()
      .includes(needle)
  })
}

export function getTemplate(id: string | undefined): BuiltInTemplate | undefined {
  if (!id) return undefined
  return BUILT_IN_TEMPLATES.find((template) => template.id === id)
}

export function templateMatches(template: BuiltInTemplate, query: string): boolean {
  return listTemplates({ query }).some((item) => item.id === template.id)
}
