import { useEffect, useRef, useState } from "react"
import { ApiError, type Artifact, api, type QuoteEditInput } from "@/api"
import { toast } from "@/components/ui/sonner"
import { useApiMutation } from "@/lib/use-api-mutation"

const clip = (s: string, n = 28): string => (s.length > n ? `${s.slice(0, n - 1)}…` : s)

// The auto version message: a single edit reads as what changed; a batch as a count.
const editMessage = (edits: QuoteEditInput[]): string => {
  const first = edits[0]
  return edits.length === 1 && first
    ? `Inline edit: "${clip(first.quote.exact.trim())}" → "${clip(first.new_text.trim())}"`
    : `Inline edits (${edits.length})`
}

/**
 * The host half of inline editing (click-to-type in the rendered artifact). The
 * frame owns the caret, the snapshots, and the diff→quote construction; this hook
 * owns the MODE — entering it (freezing the shown version so an SSE republish can't
 * reload the frame and wipe typed text), the dirty count the save bar shows, and
 * landing the collected quote edits through publish (editors) or propose
 * (commenters / locked artifacts) with the shared error grammar:
 *
 *  - 409 (a publish raced ours): refetch the head; edits stay in the frame, saving
 *    again re-resolves them against the new version.
 *  - 400 (a quote didn't resolve — formatted markdown spans, markup-crossing
 *    selections): surface the server's precise reason, offer the source editor.
 */
export function useInlineEdit(p: {
  shortId: string
  art: Artifact | undefined
  post: (msg: Record<string, unknown>) => void
  load: () => void
  /** The fallback surface when a quote can't be applied inline. */
  onOpenSourceEditor: () => void
  /** Clear selection/composer state the moment edit mode opens. */
  onEnter?: () => void
}) {
  const [active, setActive] = useState(false)
  const [dirty, setDirty] = useState(0)
  // The version the rendered frame is pinned to while editing. Freezing it keeps
  // `rawSrc` stable, so a concurrent publish updates metadata without reloading the
  // iframe out from under the user's typed-but-unsaved text.
  const [frozenVersion, setFrozenVersion] = useState<number | null>(null)
  const collectWait = useRef<{ resolve: (e: QuoteEditInput[]) => void; timer: number } | null>(null)

  // The frame's edit-* messages ride the same postMessage channel as the anchor
  // protocol; listening here keeps the central frame router untouched.
  useEffect(() => {
    const onMsg = (e: MessageEvent) => {
      const d = e.data
      if (!d || d.source !== "derive") return
      if (d.type === "edit-state") {
        setDirty(typeof d.dirty === "number" ? d.dirty : 0)
      } else if (d.type === "edit-edits") {
        const w = collectWait.current
        if (w) {
          collectWait.current = null
          clearTimeout(w.timer)
          w.resolve(Array.isArray(d.edits) ? (d.edits as QuoteEditInput[]) : [])
        }
      } else if (d.type === "edit-blocked") {
        // A click landed somewhere inline editing can't reach. Quiet + deduped —
        // information, not an alarm.
        toast(
          d.reason === "dynamic"
            ? "That part is generated by the page's own script, so it can't be edited inline."
            : "That control can't be edited inline.",
          { id: "inline-edit-blocked" },
        )
      }
    }
    window.addEventListener("message", onMsg)
    return () => window.removeEventListener("message", onMsg)
  }, [])

  const collect = (): Promise<QuoteEditInput[]> =>
    new Promise((resolve, reject) => {
      const timer = window.setTimeout(() => {
        collectWait.current = null
        reject(new Error("The page didn't report its edits. Try again."))
      }, 4000)
      collectWait.current = { resolve, timer }
      p.post({ type: "edit-collect" })
    })

  const start = () => {
    if (!p.art || active) return
    p.onEnter?.()
    setFrozenVersion(p.art.current_version)
    setDirty(0)
    setActive(true)
    p.post({ type: "edit-mode", on: true })
  }
  // Done only ever exits CLEAN (the bar swaps to Discard/Save once dirty); the
  // frame-side mode-off also restores any stragglers as a belt-and-suspenders.
  const done = () => {
    setActive(false)
    setFrozenVersion(null)
    setDirty(0)
    p.post({ type: "edit-mode", on: false })
  }
  const discard = () => p.post({ type: "edit-restore" })

  const save = useApiMutation({
    mutationFn: async () => {
      const art = p.art
      if (!art) throw new Error("save fired before the artifact loaded")
      const edits = await collect()
      if (!edits.length) return null
      // Base = the CURRENT head, not the frozen view: if a publish landed mid-edit,
      // the quotes re-resolve against the new source (the strict matcher refuses
      // anything that moved), which is the closest thing to a clean auto-merge.
      const base = art.current_version
      const message = editMessage(edits)
      const canPublish = (art.my_role === "editor" || art.my_role === "owner") && !art.locked
      if (canPublish) {
        const a = await api.publishEdits(p.shortId, edits, base, message)
        return { kind: "published" as const, version: a.current_version }
      }
      await api.proposeEdits(p.shortId, edits, base, message)
      return { kind: "proposed" as const, version: 0 }
    },
    errorToast: false,
    onSuccess: (r) => {
      if (!r) {
        done() // nothing actually changed — just leave edit mode
        return
      }
      setActive(false)
      setFrozenVersion(null)
      setDirty(0)
      toast.success(r.kind === "published" ? `Saved v${r.version}` : "Suggestion sent for review")
      p.load() // the refetch moves rawSrc to the new version; the frame reloads clean
    },
    onError: (err) => {
      if (err instanceof ApiError && err.status === 409) {
        p.load()
        toast.error("The document changed while you were editing.", {
          id: "inline-edit-conflict",
          description:
            "Your edits are still on the page. Save again to re-check them against the new version.",
          duration: 10_000,
        })
        return
      }
      // Inside useApiMutation's onError (errorToast off): the server's EditError text is
      // the product copy (WHICH edit failed and why), plus a bespoke fallback action the
      // global safety net can't carry.
      // biome-ignore format: the escape-hatch comment must stay on the toast line.
      toast.error(err instanceof ApiError ? err.message : "Couldn't save your edits.", { // mutation-ignore: bespoke server-message toast with a source-editor fallback action
        id: "inline-edit-failed",
        duration: 12_000,
        action: { label: "Open source editor", onClick: p.onOpenSourceEditor },
      })
    },
  })

  return {
    active,
    dirty,
    frozenVersion,
    saving: save.isPending,
    start,
    done,
    discard,
    save: () => save.mutate(),
  }
}
