import { type RefObject, useEffect, useRef, useState } from "react"
import { type Artifact, api, type DirUser } from "@/api"
import { toast } from "@/components/ui/sonner"
import { canPublishArtifact } from "@/lib/artifact"
import { useApiMutation } from "@/lib/use-api-mutation"
import { isUsernameQuery, isValidUsername, normalizeUsername } from "@/lib/username"
import { mentionCandidates } from "./mention-candidates"
import { askFrame } from "./use-artifact-frame"
import { type SaveStatus, useAutoSave } from "./use-auto-save"

export type { SaveStatus }

/** Leaving over edits that couldn't be saved (the message said why): one wording for
 *  Done and for navigating away. */
export const unsavedEditsCopy = {
  title: "Leave with edits that didn't save?",
  description:
    "Some edits on this page couldn't be saved. Leaving shows the page as it is saved, without them.",
  confirmLabel: "Leave without them",
}

/** One change this session, as the frame derives it: where (in block names) and what. */
export type EditChange = {
  id: string
  where: string
  what?: string
  from?: string
  to?: string
  /** The slide it sits on, in a deck. */
  slide: number | null
}
/** The selected block: its path (each crumb selects that level) and its width. */
export type EditBlock = { name: string; crumbs: string[]; resizable: boolean; width: number | null }

const str = (v: unknown): string | undefined =>
  typeof v === "string" ? v.slice(0, 200) : undefined
const changesOf = (v: unknown): EditChange[] =>
  Array.isArray(v)
    ? v.slice(0, 200).flatMap((c) => {
        if (!c || typeof c !== "object") return []
        const r = c as Record<string, unknown>
        const id = str(r.id)
        const where = str(r.where)
        if (!id || where === undefined) return []
        const slide = typeof r.slide === "number" && Number.isInteger(r.slide) ? r.slide : null
        return [{ id, where, what: str(r.what), from: str(r.from), to: str(r.to), slide }]
      })
    : []
const blockOf = (v: unknown): EditBlock | null => {
  if (!v || typeof v !== "object") return null
  const r = v as Record<string, unknown>
  const name = str(r.name)
  if (!name || !Array.isArray(r.crumbs)) return null
  return {
    name,
    crumbs: r.crumbs.slice(0, 20).map((c) => str(c) ?? ""),
    resizable: r.resizable === true,
    width: typeof r.width === "number" && Number.isFinite(r.width) ? r.width : null,
  }
}
/** A block someone else changed while you had unsaved words in it: yours or theirs. */
export type EditConflict = { id: string; where: string; mine: string; theirs: string; by: string }
const conflictsOf = (v: unknown): EditConflict[] =>
  Array.isArray(v)
    ? v.slice(0, 50).flatMap((c) => {
        if (!c || typeof c !== "object") return []
        const r = c as Record<string, unknown>
        const id = str(r.id)
        if (!id) return []
        return [
          {
            id,
            where: str(r.where) ?? "Block",
            mine: str(r.mine) ?? "",
            theirs: str(r.theirs) ?? "",
            by: str(r.by) ?? "",
          },
        ]
      })
    : []

export type InlineMentionMenuState = {
  query: string
  users: DirUser[]
  active: number
  loading: boolean
  position: { left: number; top: number }
}

type FrameMentionRect = { left: number; right: number; top: number; bottom: number }
const validMentionQuery = (value: unknown): value is string => isUsernameQuery(value)
const validMentionHandle = (value: unknown): value is string => isValidUsername(value)
const validMentionRect = (value: unknown): value is FrameMentionRect => {
  if (!value || typeof value !== "object") return false
  const r = value as Record<string, unknown>
  return [r.left, r.right, r.top, r.bottom].every(
    (n) => typeof n === "number" && Number.isFinite(n),
  )
}

/** Why the document refused a gesture, in words a reader can act on. The frame
 *  names the reason; the copy lives here so every refusal reads the same way. */
const BLOCKED_COPY: Record<string, string> = {
  control: "That control can't be edited inline.",
  dynamic: "That part is generated by the page's own script, so it can't be edited inline.",
  offscreen: "That text is on another slide. Move to it first, then edit.",
  "embedded-image":
    "That image is embedded in the page itself, so there's no file to replace. Use the source editor.",
  "format-empty": "Select the words you want to format first.",
  layout: "The page's own layout decides that, so it stays as it was.",
  "format-outside": "Select text inside the document to format it.",
  "format-range":
    "That selection is part of something bigger. Select a run of plain words instead.",
  "format-text":
    "In Markdown and LaTeX, formatting and line breaks are written as text. Type them, or use the source editor.",
  readonly:
    "Math, tables, figures and generated text can't be edited inline. Open the source editor to change them.",
  "keep-mine":
    "Their change reshaped that block, so yours can't go on top of it. Theirs is kept; type yours again.",
}

/**
 * The host half of inline editing (click-to-type in the rendered artifact). The
 * frame owns the caret, what the server holds, and what changed — exact-source ops on
 * an HTML page or Markdown document (elements named by source id; the auto-save adds
 * their hashes), quote edits on LaTeX. This hook owns the MODE — entering it, pinning
 * the shown version (a publish updates metadata; the page takes new versions in place,
 * never by reloading under typed text), the session's changes and status, and leaving.
 *
 * Every edit saves itself (see use-auto-save): there is no Save, no Discard, and no
 * reload after a save. Done flushes what's left and finishes the session.
 */
export function useInlineEdit(p: {
  shortId: string
  art: Artifact | undefined
  /** The artifact iframe — inbound edit messages are accepted from THIS window only. */
  frameRef: RefObject<HTMLIFrameElement | null>
  post: (msg: Record<string, unknown>) => void
  load: () => void
  /** The fallback surface when an edit can't be expressed inline. */
  onOpenSourceEditor: () => void
  /** Load the frame fresh on the current version, keeping the reader's place (the
   *  fallback when a version can't be taken in place). */
  reloadFrame: () => void
  /** The frame now shows `version`'s content, taken in place. */
  onSynced?: (version: number) => void
  /** A version this page saved. */
  onOwnVersion?: (version: number) => void
  /** Who made `version`, for the name on their edit as it lands. */
  authorOf: (version: number) => string
  /** Clear selection/composer state the moment edit mode opens. */
  onEnter?: () => void
  /** The block pill's ⋯: show the block's path and exact width in the edit panel. */
  onBlockMore?: () => void
  /** This viewer could open the mode right now (permission, current version, not a
   *  bundle). Gates every entry point — the header button, the
   *  `e` shortcut, and the Edit verb on a selection. */
  canEdit: boolean
  /** The stored source can carry selector-scoped element operations. Markdown is
   *  rendered as HTML in the frame, but does not support that source operation. */
  allowElementEdits: boolean
}) {
  // The version the frame's content is at while editing — the mode flag AND the pin in
  // one value (active ⇔ non-null). It moves as saves sync in; the frame never reloads
  // for it.
  const [frozenVersion, setFrozenVersion] = useState<number | null>(null)
  /** What the bar's controls can do at this instant, as the document reports it. */
  const [tools, setTools] = useState({
    canUndo: false,
    canRedo: false,
    canFormat: false,
    textActive: false,
    textKind: "",
    selectedText: "",
  })
  const [changes, setChanges] = useState<EditChange[]>([])
  const [conflicts, setConflicts] = useState<EditConflict[]>([])
  const [block, setBlock] = useState<EditBlock | null>(null)
  // Done over edits that can't be saved (an error the person must see): the confirm.
  const [exitPrompt, setExitPrompt] = useState(false)
  const [closing, setClosing] = useState(false)
  const active = frozenVersion !== null
  const activeRef = useRef(false)
  activeRef.current = active
  const [mention, setMention] = useState<InlineMentionMenuState | null>(null)
  const mentionRef = useRef<InlineMentionMenuState | null>(null)
  mentionRef.current = mention
  // A directory response can arrive after the caret moved on. Its number is local
  // to this edit session, so stale results can never replace the current token's menu.
  const mentionRequest = useRef(0)
  const mentionRenderRequest = useRef(0)
  const artRef = useRef(p.art)
  artRef.current = p.art
  // The listener is registered once; these bridge it to the current closures.
  const swapImageRef = useRef<(src: string) => void>(() => {})
  const mentionQueryRef = useRef<(query: string, rect: FrameMentionRect) => void>(() => {})
  const mentionKeyRef = useRef<(key: string) => void>(() => {})
  const blockMoreRef = useRef<() => void>(() => {})
  const renderMentionHandlesRef = useRef<(handles: unknown) => void>(() => {})
  const deletedRef = useRef<(label: string) => void>(() => {})
  const canEditRef = useRef(false)
  canEditRef.current = p.canEdit

  const ask = async <T>(type: string, payload: Record<string, unknown>, reply: string) => {
    const w = p.frameRef.current?.contentWindow
    const answer = await askFrame<T>(w, { ...payload, type }, reply, 6000)
    if (!answer) throw new Error("The page didn't answer. Try again.")
    return answer
  }

  const autoSave = useAutoSave({
    shortId: p.shortId,
    art: () => artRef.current,
    active: () => activeRef.current,
    live: () => artRef.current?.live_save === true,
    ask,
    onSynced: (version) => {
      setFrozenVersion((v) => (v === null ? v : version))
      p.onSynced?.(version)
    },
    onOwnVersion: (version) => p.onOwnVersion?.(version),
    reloadFrame: p.reloadFrame,
    authorOf: p.authorOf,
    load: p.load,
    onOpenSourceEditor: () => {
      void leave()
      p.onOpenSourceEditor()
    },
  })
  const autoSaveRef = useRef(autoSave)
  autoSaveRef.current = autoSave

  // Every way out of the mode funnels through here. Nothing is restored: every edit
  // is saved (or queued), so the text on the page is the text that stays.
  const exit = () => {
    mentionRequest.current++
    mentionRenderRequest.current++
    setMention(null)
    setFrozenVersion(null)
    setChanges([])
    setConflicts([])
    setBlock(null)
    setTools({
      canUndo: false,
      canRedo: false,
      canFormat: false,
      textActive: false,
      textKind: "",
      selectedText: "",
    })
    setExitPrompt(false)
    setClosing(false)
    autoSaveRef.current.end()
    p.post({ type: "edit-mode", on: false })
  }

  // Leaving the artifact ends the session: without this, edit mode (and the pinned
  // version) would ride along to the NEXT artifact the user navigates to.
  // biome-ignore lint/correctness/useExhaustiveDependencies: keyed to the artifact change.
  useEffect(() => {
    mentionRequest.current++
    mentionRenderRequest.current++
    if (activeRef.current) autoSaveRef.current.end()
    setFrozenVersion(null)
    setMention(null)
  }, [p.shortId])

  // A page going away finishes the session (its saves are one version, announced once).
  useEffect(() => {
    const onHide = () => {
      if (activeRef.current) autoSaveRef.current.leave()
    }
    window.addEventListener("pagehide", onHide)
    return () => window.removeEventListener("pagehide", onHide)
  }, [])

  // The frame's edit-* messages ride the same postMessage channel as the anchor
  // protocol; listening here keeps the central frame router untouched.
  //
  // Trust boundary, stated plainly: this is a WRITE path fed by the sandboxed
  // frame, so inbound messages are accepted only from the artifact iframe's own
  // window — a popup or a nested iframe inside the artifact can't speak here. What
  // that check cannot do is distinguish the injected client from the artifact's OWN
  // scripts (they share the window), which is the protocol's standing model for
  // every message (select, anchor-click, deck…). The blast radius of a forged
  // edit is bounded: it can alter escaped/sanitized text, a confidently-matched
  // element's size, or direct children of an explicitly authored structural region,
  // only while this signed-in editor has the mode open, and the version history
  // records the exact source change.
  // biome-ignore lint/correctness/useExhaustiveDependencies: frameRef is a stable ref object; reading .current at event time is the point.
  useEffect(() => {
    const onMsg = (e: MessageEvent) => {
      if (!p.frameRef.current?.contentWindow || e.source !== p.frameRef.current.contentWindow)
        return
      const d = e.data
      if (d?.source !== "derive") return
      if (d.type === "edit-state") {
        // What the bar's controls can offer right now. A client cached from before
        // these existed reports none of them, and the controls stay quiet rather
        // than promising something the document can't do.
        setTools({
          canUndo: !!d.canUndo,
          canRedo: !!d.canRedo,
          canFormat: !!d.canFormat,
          textActive: !!d.textActive,
          textKind: typeof d.textKind === "string" ? d.textKind : "",
          selectedText: typeof d.selectedText === "string" ? d.selectedText : "",
        })
        if (Array.isArray(d.changes)) setChanges(changesOf(d.changes))
        setConflicts(conflictsOf(d.conflicts))
        setBlock(blockOf(d.block))
      } else if (d.type === "edit-touch") {
        if (activeRef.current && typeof d.rev === "number")
          autoSaveRef.current.touch(d.rev, !!d.flush)
      } else if (d.type === "edit-base") {
        if (activeRef.current && typeof d.version === "number" && typeof d.sha === "string") {
          setFrozenVersion(d.version)
          autoSaveRef.current.based(d.version, d.sha)
        }
      } else if (d.type === "edit-deleted") {
        if (activeRef.current) deletedRef.current(typeof d.label === "string" ? d.label : "")
      } else if (d.type === "edit-block-more") {
        if (activeRef.current) blockMoreRef.current()
      } else if (d.type === "edit-save") {
        // ⌘S / ⌘Enter inside the frame: save now rather than after the pause.
        if (activeRef.current) autoSaveRef.current.flush()
      } else if (d.type === "edit-image") {
        if (canEditRef.current && typeof d.src === "string") swapImageRef.current(d.src)
      } else if (d.type === "edit-mention-query") {
        if (activeRef.current && validMentionQuery(d.query) && validMentionRect(d.rect))
          mentionQueryRef.current(d.query, d.rect)
      } else if (d.type === "edit-mention-key") {
        if (activeRef.current && typeof d.key === "string") mentionKeyRef.current(d.key)
      } else if (d.type === "edit-mention-close") {
        mentionRequest.current++
        setMention(null)
      } else if (d.type === "mention-resolve") {
        renderMentionHandlesRef.current(d.handles)
      } else if (d.type === "edit-blocked") {
        // A click landed somewhere inline editing can't reach. Quiet + deduped —
        // information, not an alarm.
        toast(BLOCKED_COPY[String(d.reason)] ?? BLOCKED_COPY.control, {
          id: "inline-edit-blocked",
        })
      }
    }
    window.addEventListener("message", onMsg)
    return () => window.removeEventListener("message", onMsg)
  }, [])

  /** "Deleted Card 2 · Undo": its save waits while Undo is on screen, so Undo simply
   *  puts it back; the toast leaving (or anything else saving) lets it go. */
  deletedRef.current = (label) => {
    autoSave.hold(5000)
    toast(label ? `Deleted ${label}` : "Deleted a block", {
      id: "inline-edit-deleted",
      duration: 5000,
      action: {
        label: "Undo",
        onClick: () => {
          p.post({ type: "edit-undo-delete" })
          autoSaveRef.current.release()
        },
      },
      onAutoClose: () => autoSaveRef.current.release(),
      onDismiss: () => autoSaveRef.current.release(),
    })
  }

  const dismissMention = () => {
    mentionRequest.current++
    setMention(null)
    p.post({ type: "edit-mention-close" })
  }
  const chooseMention = (user: DirUser) => {
    const handle = user.handle
    if (!validMentionHandle(handle)) return
    mentionRequest.current++
    setMention(null)
    p.post({ type: "edit-mention-insert", handle })
  }
  const positionMention = (rect: FrameMentionRect): { left: number; top: number } | null => {
    const frame = p.frameRef.current?.getBoundingClientRect()
    if (!frame) return null
    // Fixed coordinates in the host viewport. Keep the menu fully visible on a
    // narrow screen; the caret remains visible in the iframe directly beneath it.
    return {
      left: Math.max(8, Math.min(window.innerWidth - 296, frame.left + rect.left)),
      top: Math.max(8, Math.min(window.innerHeight - 230, frame.top + rect.bottom + 8)),
    }
  }
  mentionQueryRef.current = (query, rect) => {
    const position = positionMention(rect)
    if (!position) return
    const request = ++mentionRequest.current
    setMention({ query, users: [], active: 0, loading: true, position })
    // A directory failure is intentionally cosmetic: the raw handle remains in the
    // document and publish-time resolution still has its normal safe behavior.
    mentionCandidates(query, p.shortId)
      .then((users) => {
        if (request !== mentionRequest.current || !activeRef.current) return
        setMention({ query, users, active: 0, loading: false, position })
      })
      .catch(() => {
        if (request !== mentionRequest.current || !activeRef.current) return
        setMention((current) =>
          current?.query === query ? { ...current, users: [], loading: false } : current,
        )
      })
  }
  renderMentionHandlesRef.current = (value) => {
    if (!Array.isArray(value)) return
    const requested = new Set(
      value.filter(validMentionHandle).map((handle) => normalizeUsername(handle)),
    )
    if (!requested.size) {
      p.post({ type: "mention-render", handles: [] })
      return
    }
    const request = ++mentionRenderRequest.current
    // Resolve once per document frame. The endpoint returns only handles already
    // present in this artifact, rather than exposing a workspace roster to a
    // public-link reader; the iframe has no authenticated directory access itself.
    api
      .artifactMentionHandles(p.shortId)
      .then(({ handles }) => {
        if (request !== mentionRenderRequest.current) return
        p.post({
          type: "mention-render",
          handles: handles
            .filter(validMentionHandle)
            .map((handle) => normalizeUsername(handle))
            .filter((handle) => requested.has(handle)),
        })
      })
      .catch(() => {
        if (request === mentionRenderRequest.current)
          p.post({ type: "mention-render", handles: [] })
      })
  }
  mentionKeyRef.current = (key) => {
    const current = mentionRef.current
    if (!current) return
    if (key === "Escape") {
      dismissMention()
      return
    }
    if (!current.users.length) return
    if (key === "ArrowDown") {
      setMention({ ...current, active: (current.active + 1) % current.users.length })
      return
    }
    if (key === "ArrowUp") {
      setMention({
        ...current,
        active: (current.active - 1 + current.users.length) % current.users.length,
      })
      return
    }
    if (key === "Enter" || key === "Tab") {
      const user = current.users[current.active]
      if (user) chooseMention(user)
    }
  }

  /** Open the mode. `entry` names the gesture that opened it — the Edit verb on a
   *  live selection — so the caret lands on the words the user was already looking
   *  at instead of making them click again. Omitted for the header button and the
   *  `e` shortcut: the mode opens, and the first click chooses the block. */
  const start = (entry?: { fromSelection?: boolean }) => {
    if (!p.art || active) return
    p.onEnter?.()
    mentionRequest.current++
    setMention(null)
    setChanges([])
    setConflicts([])
    setBlock(null)
    setFrozenVersion(p.art.current_version)
    autoSave.begin()
    p.post({ type: "edit-mode", on: true, elementEdits: p.allowElementEdits, ...entry })
  }
  /** Done: save what's left, finish the session, leave. Edits that can't be saved
   *  (an error the person must see) ask first; a conflict must be settled first. */
  /** Resolves true once the mode is left (false: a question is pending first). */
  const done = async (): Promise<boolean> => {
    if (!activeRef.current) return true
    if (closing) return false
    setClosing(true)
    await autoSave.settle()
    setClosing(false)
    if (!activeRef.current) return true
    const st = autoSaveRef.current.status(conflicts.length)
    if (st.kind === "conflict") {
      toast("Choose whose words to keep first.", { id: "inline-edit-done" })
      return false
    }
    if (st.kind === "error" || st.kind === "pending") {
      setExitPrompt(true)
      return false
    }
    const n = changes.length
    exit()
    toast(
      st.kind === "offline"
        ? `Done · ${st.waiting || "Your"} edit${st.waiting === 1 ? "" : "s"} will save when you're back online`
        : n
          ? `Done · ${n} change${n === 1 ? "" : "s"} saved`
          : "Done",
      { id: "inline-edit-done" },
    )
    return true
  }
  /** Escape and the header's Edit toggle: the same as Done. */
  const requestExit = () => void done()
  /** The confirm's answer: leave with what couldn't be saved left on the page as-is,
   *  then show the page as the server has it. */
  const confirmExit = () => {
    exit()
    p.reloadFrame()
  }
  const cancelExit = () => setExitPrompt(false)
  /** Leave at once (the source editor is opening over it). */
  const leave = async () => {
    if (!activeRef.current) return
    await autoSave.settle()
    if (activeRef.current) exit()
  }
  /** The bar's controls. Each one is the same call the keyboard chord makes inside
   *  the document, so a button and its shortcut can never drift apart. A link needs
   *  a URL, which the bar asks for before sending it. */
  const undo = () => p.post({ type: "edit-undo" })
  const redo = () => p.post({ type: "edit-redo" })
  const format = (kind: "b" | "i" | "a", href?: string) =>
    p.post({ type: "edit-format", kind, href })
  /** The session list and the block panel speak to the frame by id and index. */
  const revealChange = (id: string) => p.post({ type: "edit-reveal", id })
  const revertChange = (id: string) => p.post({ type: "edit-revert", id })
  const resolveConflict = (id: string, mine: boolean) => p.post({ type: "edit-resolve", id, mine })
  const selectCrumb = (index: number) => p.post({ type: "edit-block-crumb", index })
  const setBlockWidth = (width: number | null) => p.post({ type: "edit-block-width", width })
  blockMoreRef.current = () => p.onBlockMore?.()
  /** The frame reloaded (a version it couldn't take in place, a retry). Everything
   *  was saved before any such reload, so the session carries on in the new page. */
  const onFrameGone = () => {
    mentionRequest.current++
    setMention(null)
    if (!activeRef.current) return
    setFrozenVersion(artRef.current?.current_version ?? frozenVersion ?? 0)
    autoSave.frameGone()
    p.post({ type: "edit-mode", on: true, elementEdits: p.allowElementEdits })
  }

  /**
   * Replace a picture. Clicked in the document, picked from disk, uploaded as an
   * asset, and swapped by its URL — the one edit here that isn't text.
   *
   * It saves on its own, as a literal source swap (an image URL lives in an attribute,
   * where there is no visible text to quote), so the history reads "Replaced an image"
   * as its own revision. The page then takes the new version in like anyone's edit.
   *
   * Only for someone who can publish.
   */
  const imageSwap = useApiMutation({
    mutationFn: async (v: { file: File; oldSrc: string; base: number }) => {
      const asset = await api.uploadAsset(v.file)
      return api.publishEdits(
        p.shortId,
        [{ old_str: v.oldSrc, new_str: asset.url }],
        v.base,
        "Replaced an image",
      )
    },
    success: "Image replaced",
    onSuccess: () => {
      p.load()
      if (activeRef.current) autoSaveRef.current.remote()
      else p.reloadFrame()
    },
  })
  const swapImage = (oldSrc: string) => {
    const art = p.art
    if (!art || !canPublishArtifact(art)) {
      toast("Replacing an image needs edit access on this artifact.", { id: "inline-edit-image" })
      return
    }
    const input = document.createElement("input")
    input.type = "file"
    // What the asset route actually accepts (it sniffs magic bytes, and refuses SVG).
    input.accept = "image/png,image/jpeg,image/gif,image/webp"
    input.onchange = () => {
      const file = input.files?.[0]
      if (file) imageSwap.mutate({ file, oldSrc, base: art.current_version })
    }
    input.click()
  }
  swapImageRef.current = swapImage

  const status = autoSave.status(conflicts.length)
  return {
    active,
    /** Echoed back so the page's `e` shortcut and the selection bar ask ONE source
     *  whether the mode is available, rather than re-deriving eligibility. */
    canEdit: p.canEdit,
    /** Where the auto-save is: Edited / Saving… / All changes saved / Offline / … */
    status,
    /** Live capability of the bar's controls (undo / redo / format). */
    tools,
    /** This session's changes, and the selected block, as the frame reports them. */
    changes,
    conflicts,
    block,
    revealChange,
    revertChange,
    resolveConflict,
    selectCrumb,
    setBlockWidth,
    /** Whether this source format can persist selector-scoped element operations. */
    allowElementEdits: p.allowElementEdits,
    undo,
    redo,
    format,
    frozenVersion,
    closing,
    /** Anything the server doesn't hold yet — drives the unload/navigation guard. */
    unsaved: autoSave.unsaved,
    /** Someone else published while the mode is open: take it in, in place. */
    remote: autoSave.remote,
    exitPrompt,
    start,
    done,
    requestExit,
    confirmExit,
    cancelExit,
    mention,
    chooseMention,
    dismissMention,
    onFrameGone,
    /** Save now (⌘S). */
    save: autoSave.flush,
    /** Edits save themselves; otherwise the bar offers Save. */
    live: p.art?.live_save === true,
  }
}
