import { type RefObject, useEffect, useRef, useState } from "react"
import { ApiError, type Artifact, api, type QuoteEditInput } from "@/api"
import { toast } from "@/components/ui/sonner"
import { canPublishArtifact } from "@/lib/artifact"
import { useApiMutation } from "@/lib/use-api-mutation"

const clip = (s: string, n = 28): string => (s.length > n ? `${s.slice(0, n - 1)}…` : s)

/** One wording for "you are about to lose edits", wherever the user tries to leave:
 *  in-app navigation (the blocker), Escape, and Done. */
export const unsavedEditsCopy = (n: number) => ({
  title: "Discard your unsaved edits?",
  description: `This document has ${n} unsaved change${n === 1 ? "" : "s"}. Leaving now discards ${n === 1 ? "it" : "them"} — that can't be undone.`,
  confirmLabel: "Discard edits",
})

// The auto version message: a single edit reads as what changed; a batch as a count.
// A formatting edit carries markup rather than text, and saying so is more useful in
// the history than quoting tags at someone. (Reading `new_text` unconditionally used
// to throw here — the save died before it reached the network, and the failure
// surfaced as a bare "couldn't save".)
const editMessage = (edits: QuoteEditInput[]): string => {
  const first = edits[0]
  if (edits.length !== 1 || !first) return `Inline edits (${edits.length})`
  if (first.new_text === undefined) return `Inline formatting: "${clip(first.quote.exact.trim())}"`
  return `Inline edit: "${clip(first.quote.exact.trim())}" → "${clip(first.new_text.trim())}"`
}

type SaveOutcome = { kind: "published"; version: number } | { kind: "proposed" } | null

/** Why the document refused a gesture, in words a reader can act on. The frame
 *  names the reason; the copy lives here so every refusal reads the same way. */
const BLOCKED_COPY: Record<string, string> = {
  control: "That control can't be edited inline.",
  dynamic: "That part is generated by the page's own script, so it can't be edited inline.",
  offscreen: "That text is on another slide. Move to it first, then edit.",
  "embedded-image":
    "That image is embedded in the page itself, so there's no file to replace. Use the source editor.",
  "format-empty": "Select the words you want to format first.",
  "format-outside": "Select text inside the document to format it.",
  "format-range":
    "That selection is part of something bigger. Select a run of plain words instead.",
}

/**
 * The host half of inline editing (click-to-type in the rendered artifact). The
 * frame owns the caret, the snapshots, and the diff→quote construction; this hook
 * owns the MODE — entering it (freezing the shown version so an SSE republish can't
 * reload the frame and wipe typed text), the dirty count the save bar shows, and
 * landing the collected quote edits through publish (editors) or propose
 * (commenters / locked artifacts) with the shared error grammar:
 *
 *  - 409 (a publish raced ours): refetch the head; edits stay in the frame, saving
 *    again re-resolves them against the new version.
 *  - 400 (a quote didn't resolve — formatted markdown spans, markup-crossing
 *    selections): surface the server's precise reason, offer the source editor.
 *
 * The session is bounded by the FRAME's lifetime: `onFrameGone` (wired to the
 * page's iframe onLoad) force-exits with a warning, because a reloaded frame boots
 * with no edit state and silently saving nothing would read as success.
 */
export function useInlineEdit(p: {
  shortId: string
  art: Artifact | undefined
  /** The artifact iframe — inbound edit messages are accepted from THIS window only. */
  frameRef: RefObject<HTMLIFrameElement | null>
  post: (msg: Record<string, unknown>) => void
  load: () => void
  /** The fallback surface when a quote can't be applied inline. */
  onOpenSourceEditor: () => void
  /** Clear selection/composer state the moment edit mode opens. */
  onEnter?: () => void
  /** This viewer could open the mode right now (permission, current version, not a
   *  bundle, not GitHub-managed). Arms the document's own entry gesture: a
   *  double-click asks to edit there. A reader who can't save never fires one. */
  canEdit: boolean
}) {
  // The version the rendered frame is pinned to while editing — the mode flag AND
  // the freeze in one value (active ⇔ non-null), so no exit path can ever leave
  // the two disagreeing. Freezing keeps `rawSrc` stable, so a concurrent publish
  // updates metadata without reloading the iframe out from under typed text.
  const [frozenVersion, setFrozenVersion] = useState<number | null>(null)
  const [dirty, setDirty] = useState(0)
  /** What the bar's controls can do at this instant, as the document reports it. */
  const [tools, setTools] = useState({ canUndo: false, canRedo: false, canFormat: false })
  // Escape (or Done) pressed with unsaved edits: the confirm the page renders.
  const [exitPrompt, setExitPrompt] = useState(false)
  const active = frozenVersion !== null
  const activeRef = useRef(false)
  activeRef.current = active
  const dirtyRef = useRef(0)
  dirtyRef.current = dirty
  const collectWait = useRef<{
    nonce: number
    resolve: (e: QuoteEditInput[] | { desync: true }) => void
    timer: number
  } | null>(null)
  const nonceSeq = useRef(0)
  // The listener is registered once; the save mutation is created below it. A ref
  // bridges the two without re-subscribing the listener on every render.
  const saveRef = useRef<() => void>(() => {})
  const savingRef = useRef(false)
  // Same bridge for the inbound entry request (see `start` below) and for an image
  // click (see `swapImage`) — the listener is registered once and must reach the
  // current closures.
  const startRef = useRef<(entry?: { fromPointer?: boolean }) => void>(() => {})
  const swapImageRef = useRef<(src: string) => void>(() => {})
  const canEditRef = useRef(false)
  canEditRef.current = p.canEdit

  // Every way out of the mode funnels through here.
  //   "restore" — revert unsaved text and re-arm the read grammar (Done, Escape,
  //               discard-and-leave, and a filed PROPOSAL: nothing is live until
  //               approval, so the page must not keep the suggestion painted).
  //   "settle"  — keep the text, drop the editing chrome. Right after a PUBLISH the
  //               text on screen IS what was saved; restoring would flash the old
  //               wording for the beat before the version swap reloads the frame.
  //   "none"    — the frame is already gone (reload); there is nothing to talk to.
  const exit = (frame: "restore" | "settle" | "none") => {
    setFrozenVersion(null)
    setDirty(0)
    setTools({ canUndo: false, canRedo: false, canFormat: false })
    setExitPrompt(false)
    if (frame === "restore") p.post({ type: "edit-mode", on: false })
    else if (frame === "settle") p.post({ type: "edit-mode", on: false, keep: true })
  }

  // Leaving the artifact ends the session: without this, edit mode (and the frozen
  // version) would ride along to the NEXT artifact the user navigates to, pinning
  // its shown version to a number from a different document.
  // biome-ignore lint/correctness/useExhaustiveDependencies: keyed to the artifact change.
  useEffect(() => {
    setFrozenVersion(null)
    setDirty(0)
  }, [p.shortId])

  // The frame's edit-* messages ride the same postMessage channel as the anchor
  // protocol; listening here keeps the central frame router untouched.
  //
  // Trust boundary, stated plainly: this is a WRITE path fed by the sandboxed
  // frame, so inbound messages are accepted only from the artifact iframe's own
  // window — a popup or a nested iframe inside the artifact can't speak here. What
  // that check cannot do is distinguish the injected client from the artifact's OWN
  // scripts (they share the window), which is the protocol's standing model for
  // every message (select, anchor-click, deck…). The blast radius of a forged
  // edit-edits is bounded: it can only alter TEXT of the artifact the author
  // already controls (replacements are escaped / re-sanitized at render), the save
  // still requires this signed-in user's deliberate Save click, and the version
  // history records the exact spans changed.
  // biome-ignore lint/correctness/useExhaustiveDependencies: frameRef is a stable ref object; reading .current at event time is the point.
  useEffect(() => {
    const onMsg = (e: MessageEvent) => {
      if (!p.frameRef.current?.contentWindow || e.source !== p.frameRef.current.contentWindow)
        return
      const d = e.data
      if (d?.source !== "derive") return
      if (d.type === "edit-state") {
        setDirty(typeof d.dirty === "number" ? d.dirty : 0)
        // What the bar's controls can offer right now. A client cached from before
        // these existed reports none of them, and the controls stay quiet rather
        // than promising something the document can't do.
        setTools({
          canUndo: !!d.canUndo,
          canRedo: !!d.canRedo,
          canFormat: !!d.canFormat,
        })
      } else if (d.type === "edit-edits") {
        const w = collectWait.current
        // The nonce pins the reply to THIS collect: a slow page can answer a
        // timed-out collect after a newer one started, and those stale edits must
        // not save (they'd be missing the user's latest typing). A client cached
        // from before the nonce existed (the served client has a 5-minute cache, so
        // this is every deploy's first few minutes) replies without one — accept
        // that rather than making saving look broken until the cache turns over.
        if (!w || (d.nonce !== undefined && d.nonce !== w.nonce)) return
        collectWait.current = null
        clearTimeout(w.timer)
        const edits = Array.isArray(d.edits) ? (d.edits as QuoteEditInput[]) : []
        // Blocks the frame changed but could NOT express as an edit. Saving the rest
        // would publish some of the user's work and let the post-save reload wipe
        // the remainder — data loss presented as success. `uncaptured` is reported
        // per block, because one dirty block can legitimately yield several edits, so
        // counts alone can't tell a partial failure from a normal multi-edit save.
        const uncaptured = typeof d.uncaptured === "number" ? d.uncaptured : 0
        const frameDirty = typeof d.dirty === "number" ? d.dirty : 0
        const lost = uncaptured > 0 || (edits.length === 0 && frameDirty > 0)
        w.resolve(lost ? { desync: true } : edits)
      } else if (d.type === "edit-save") {
        // ⌘S / ⌘Enter pressed inside the frame. Deliberately NOT gated on the dirty
        // count: that number arrives on a debounce, and gating on it dropped the
        // save when you typed and hit ⌘S in one motion — with the frame having
        // already swallowed the browser's own Save dialog, so nothing happened at
        // all. A save with nothing to collect is a no-op (see onSuccess), and the
        // in-flight guard is what stops key-repeat from stacking versions.
        if (activeRef.current && !savingRef.current) saveRef.current()
      } else if (d.type === "edit-request") {
        // A double-click on the text: the document asking to become editable there.
        // Re-checked against the CURRENT permission rather than trusting the arming
        // that let the frame speak, because a stale armed flag (a version swap, a
        // lock landing over SSE) must not open a mode this viewer can't save from.
        if (canEditRef.current && !activeRef.current) startRef.current({ fromPointer: true })
      } else if (d.type === "edit-image") {
        if (canEditRef.current && typeof d.src === "string") swapImageRef.current(d.src)
      } else if (d.type === "edit-blocked") {
        // A click landed somewhere inline editing can't reach. Quiet + deduped —
        // information, not an alarm.
        toast(BLOCKED_COPY[String(d.reason)] ?? BLOCKED_COPY.control, {
          id: "inline-edit-blocked",
        })
      }
    }
    window.addEventListener("message", onMsg)
    return () => window.removeEventListener("message", onMsg)
  }, [])

  const collect = (): Promise<QuoteEditInput[] | { desync: true }> =>
    new Promise((resolve, reject) => {
      const nonce = ++nonceSeq.current
      const timer = window.setTimeout(() => {
        // Only clear the slot if it is still OURS — a newer collect may already own
        // it, and nulling that one would strand a save that can never resolve.
        if (collectWait.current?.nonce === nonce) collectWait.current = null
        reject(new Error("The page didn't report its edits. Try again."))
      }, 4000)
      collectWait.current = { nonce, resolve, timer }
      p.post({ type: "edit-collect", nonce })
    })

  /** Open the mode. `entry` names the gesture that opened it — the frame's own
   *  double-click (whose target the client already captured) or the live selection
   *  (the Edit verb on a selection) — so the caret lands on the words the user was
   *  already looking at instead of making them click again. Omitted for the header
   *  button: the mode opens, and the first click chooses the block. */
  const start = (entry?: { fromPointer?: boolean; fromSelection?: boolean }) => {
    if (!p.art || active) return
    p.onEnter?.()
    setDirty(0)
    setFrozenVersion(p.art.current_version)
    p.post({ type: "edit-mode", on: true, ...entry })
  }
  startRef.current = start
  // Tell the frame whether the document's own entry gesture is live. Re-posted on
  // every change AND after a frame (re)load, because a fresh document boots with the
  // flag off and would otherwise stay un-armed until something else changed.
  const armed = p.canEdit && !active
  // biome-ignore lint/correctness/useExhaustiveDependencies: `post` is recreated per render by design; the flag is what this syncs.
  useEffect(() => {
    p.post({ type: "edit-armed", on: armed })
  }, [armed])
  // Done only ever exits CLEAN (the bar swaps to Discard/Save once dirty); the
  // frame-side mode-off also restores any stragglers as a belt-and-suspenders.
  /** Leave the mode. With unsaved edits this asks first — Escape and Done both land
   *  here, so "get me out" never silently throws typing away. */
  const requestExit = () => {
    if (!activeRef.current) return
    if (dirtyRef.current > 0) setExitPrompt(true)
    else exit("restore")
  }
  const done = requestExit
  /** The confirm's destructive answer: drop the edits and leave. */
  const confirmExit = () => exit("restore")
  const cancelExit = () => setExitPrompt(false)
  const discard = () => p.post({ type: "edit-restore" })
  /** The bar's controls. Each one is the same call the keyboard chord makes inside
   *  the document, so a button and its shortcut can never drift apart. A link needs
   *  a URL, which the bar asks for before sending it. */
  const undo = () => p.post({ type: "edit-undo" })
  const redo = () => p.post({ type: "edit-redo" })
  const format = (kind: "b" | "i" | "a", href?: string) =>
    p.post({ type: "edit-format", kind, href })
  /** The frame reloaded (version swap, retry, source editor) — the edit session
   *  died with it. Exit and say so if anything was pending. */
  const onFrameGone = () => {
    // A fresh document boots un-armed whatever the host last said, so re-state it.
    p.post({ type: "edit-armed", on: canEditRef.current && !activeRef.current })
    if (!activeRef.current) return
    const hadEdits = dirtyRef.current > 0
    exit("none") // the frame is a fresh document; there is nothing to restore
    if (hadEdits)
      toast.warning("The artifact reloaded, so unsaved inline edits were discarded.", {
        id: "inline-edit-stale",
      })
  }

  /**
   * Replace a picture. Clicked in the document, picked from disk, uploaded as an
   * asset, and swapped by its URL — the one edit here that isn't text.
   *
   * It saves on its own rather than joining the text batch, because the server
   * refuses a batch that mixes quote edits with literal string edits (they resolve
   * against different baselines) and an image URL lives in an attribute, where there
   * is no visible text to quote. So the history reads "Replaced an image" as its own
   * revision, which is also how a reader would describe it.
   *
   * Only for someone who can publish: routing this through review would mean
   * uploading an asset for a proposal that may never land.
   */
  const imageSwap = useApiMutation({
    mutationFn: async (v: { file: File; oldSrc: string; base: number }) => {
      const asset = await api.uploadAsset(v.file)
      return api.publishEdits(
        p.shortId,
        [{ old_str: v.oldSrc, new_str: asset.url }],
        v.base,
        "Replaced an image",
      )
    },
    success: "Image replaced",
    onSuccess: () => {
      // The frame is still showing the OLD picture and holds no unsaved text (an
      // image swap is its own revision), so let the version swap reload it.
      exit("none")
      p.load()
    },
  })
  const swapImage = (oldSrc: string) => {
    const art = p.art
    if (!art || !canPublishArtifact(art)) {
      toast("Replacing an image needs edit access on this artifact.", { id: "inline-edit-image" })
      return
    }
    const input = document.createElement("input")
    input.type = "file"
    // What the asset route actually accepts (it sniffs magic bytes, and refuses SVG).
    input.accept = "image/png,image/jpeg,image/gif,image/webp"
    input.onchange = () => {
      const file = input.files?.[0]
      if (file) imageSwap.mutate({ file, oldSrc, base: art.current_version })
    }
    input.click()
  }
  swapImageRef.current = swapImage

  const save = useApiMutation({
    mutationFn: async (): Promise<SaveOutcome | { desync: true }> => {
      const art = p.art
      if (!art) throw new Error("save fired before the artifact loaded")
      const collected = await collect()
      if ("desync" in collected) return collected
      if (!collected.length) return null
      // Base = the CURRENT head, not the frozen view: if a publish landed mid-edit,
      // the quotes re-resolve against the new source (the strict matcher refuses
      // anything that moved), which is the closest thing to a clean auto-merge.
      const base = art.current_version
      const message = editMessage(collected)
      if (canPublishArtifact(art)) {
        const a = await api.publishEdits(p.shortId, collected, base, message)
        return { kind: "published", version: a.current_version }
      }
      await api.proposeEdits(p.shortId, collected, base, message)
      return { kind: "proposed" }
    },
    errorToast: false,
    onSuccess: (r) => {
      if (r && "desync" in r) {
        // Changed blocks produced no expressible edits (typed into a spot with
        // nothing to anchor on, or the page's own script churned the DOM). Keep
        // the session so nothing is silently lost; point at the sure path.
        toast.error("Those changes couldn't be captured as text edits.", {
          id: "inline-edit-failed",
          description: "Try editing the surrounding sentence too, or use the source editor.",
          duration: 12_000,
          action: {
            label: "Open source editor",
            onClick: () => {
              exit("restore")
              p.onOpenSourceEditor()
            },
          },
        })
        return
      }
      if (!r) {
        // Nothing to save (a shortcut on a clean document, or everything reverted).
        // Stay in the mode: exiting on a no-op would make ⌘S feel like a cancel.
        return
      }
      if (r.kind === "published") {
        // The version bump reloads the frame onto the published content; posting
        // mode-off here would flash the pre-edit text for a beat first.
        exit("settle")
        toast.success(`Saved v${r.version}`)
      } else {
        // A proposal does NOT change the live document — no version bump, no frame
        // reload. Mode-off restores the pre-edit text (the suggestion lives in the
        // review queue now) and re-arms the normal read grammar; without it the
        // frame stays edit-locked forever.
        exit("restore")
        toast.success("Suggestion sent for review")
      }
      p.load()
    },
    onError: (err) => {
      if (err instanceof ApiError && err.status === 409) {
        p.load()
        toast.error("The artifact changed while you were editing.", {
          id: "inline-edit-conflict",
          description:
            "Your edits are still on the page. Save again to re-check them against the new version.",
          duration: 10_000,
        })
        return
      }
      // Inside useApiMutation's onError (errorToast off): the server's EditError text is
      // the product copy (WHICH edit failed and why), plus a bespoke fallback action the
      // global safety net can't carry. Opening the source editor ends the inline session
      // first — the editor unmounts the frame, and a phantom session pinned to a stale
      // frozen version would otherwise survive underneath it.
      // biome-ignore format: the escape-hatch comment must stay on the toast line.
      toast.error(err instanceof ApiError ? err.message : "Couldn't save your edits.", { // mutation-ignore: bespoke server-message toast with a source-editor fallback action
        id: "inline-edit-failed",
        duration: 12_000,
        action: {
          label: "Open source editor",
          onClick: () => {
            exit("restore")
            p.onOpenSourceEditor()
          },
        },
      })
    },
  })

  saveRef.current = () => save.mutate()
  savingRef.current = save.isPending

  return {
    active,
    /** Echoed back so the page's `e` shortcut and the selection bar ask ONE source
     *  whether the mode is available, rather than re-deriving eligibility. */
    canEdit: p.canEdit,
    dirty,
    /** Live capability of the bar's controls (undo / redo / format). */
    tools,
    undo,
    redo,
    format,
    frozenVersion,
    saving: save.isPending,
    /** Unsaved edits exist — drives the navigation blocker and the exit confirm. */
    blocking: active && dirty > 0,
    exitPrompt,
    start,
    done,
    discard,
    requestExit,
    confirmExit,
    cancelExit,
    onFrameGone,
    save: () => save.mutate(),
  }
}
