/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user + their active-workspace role. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The current user (SessionUser + role) and whether multi-workspace is on. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                id: string;
                                email: string;
                                name: string | null;
                                username: string | null;
                                discoverable: boolean;
                                profession: string | null;
                                about: string | null;
                                onboarded: boolean;
                                emailVerified: boolean;
                                role: string;
                            };
                            multi: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/username": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim or change your @handle. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The new handle. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            username: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set your team role + one-line bio. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The saved profession + about (null clears a field). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            profession: string | null;
                            about: string | null;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/discoverable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Opt in/out of being findable in people search. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The new discoverability. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            discoverable: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/onboarded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark first-run onboarding finished (server-authoritative). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Onboarded. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            onboarded: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search opted-in accounts by handle or name. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Matching public profiles (public fields only). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            users: components["schemas"]["PublicProfile"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse (or search) the discoverable people directory. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Public profiles (public fields only). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            users: components["schemas"]["PublicProfile"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{handle}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A public profile by @handle (email never returned). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    handle: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The public profile with stats + follow state. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: components["schemas"]["PublicProfile"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{handle}/followers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who follows this user (signed-in only). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    handle: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Followers as public profiles. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            users: components["schemas"]["PublicProfile"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{handle}/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who this user follows (signed-in only). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    handle: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Following as public profiles. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            users: components["schemas"]["PublicProfile"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload your profile picture (multipart; raster images only). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The served avatar URL. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            image: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The @mention directory: workspace people + agents (auth only). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Mentionable people + agents (by @handle, never email). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            users: components["schemas"]["DirUser"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the workspace's registered agents (Admin only). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The workspace's agents. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            agents: components["schemas"]["Agent"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Register an agent and mint its token (returned once). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The created agent, plus its bearer token (shown only here). */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Agent"] & {
                            token: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an agent (Admin only). */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The agent was deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/connected-agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the OAuth agents the signed-in user authorized to act on their behalf. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The caller's connected agents. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            agents: components["schemas"]["ConnectedAgent"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/connected-agents/{clientId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a connected agent's authorization. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clientId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The grant was revoked (idempotent). */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{shortId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List an artifact's collaborators (collaborators only). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The workspace default role and the artifact's members. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            default_role: "viewer" | "commenter" | "editor" | "owner";
                            members: components["schemas"]["ArtifactMember"][];
                        };
                    };
                };
            };
        };
        /** Share an artifact with a person at a role. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The added member. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArtifactMember"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{shortId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a collaborator from an artifact. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortId: string;
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The collaborator was removed. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{shortId}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Star an artifact. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Starred. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            favorite: boolean;
                        };
                    };
                };
            };
        };
        post?: never;
        /** Unstar an artifact. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unstarred. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            favorite: boolean;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{shortId}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set an artifact's browse tags (editors). */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The normalized tags. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            tags: string[];
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/follows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the signed-in user's follows in their active workspace. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The caller's follows. People-follows carry the followed person's public handle/name/avatar. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            follows: components["schemas"]["Follow"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Follow a GitHub author, a repo path prefix, or a person. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The created follow. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            follow: components["schemas"]["Follow"];
                        };
                    };
                };
            };
        };
        /** Remove a follow (idempotent). */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The follow was removed. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the active workspace's collections (members only). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The workspace's collections, each with its item count and origin. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            collections: components["schemas"]["Collection"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a collection. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The created collection (empty, manual). */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Collection"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/collections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a collection. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The collection was deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Rename a collection. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The updated collection. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Collection"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/collections/{id}/items/{shortId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Add an artifact to a collection. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    shortId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The artifact was added. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
            };
        };
        post?: never;
        /** Remove an artifact from a collection. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    shortId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The artifact was removed. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/collections/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a collection's members. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The collection's creator and its members. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            created_by: string;
                            members: components["schemas"]["ArtifactMember"][];
                        };
                    };
                };
            };
        };
        /** Add or update a collection member. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The added member. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArtifactMember"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/collections/{id}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a collection member. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The member was removed. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/slack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Slack connection status for the signed-in user's workspace. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Whether Slack is available + connected, and the team + default channel. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SlackStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Disconnect Slack from the workspace (Admin only). */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Slack was disconnected. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Set the channel Derive posts to (Admin only). */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The new default channel (or null to clear it). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            default_channel: string | null;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/vitals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report a Core Web Vitals field metric (anonymous telemetry). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted (sendBeacon can't read the response). */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{shortId}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report an artifact for abuse (public). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The report was filed. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The open moderation queue (Admin only). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Open reports and their count. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            reports: components["schemas"]["Report"][];
                            open: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The moderation audit log (Admin only). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recent audit-log entries. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            audit: components["schemas"]["AuditEntry"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{shortId}/takedown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Take an artifact down (Admin only); its content 410s everywhere. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The artifact was taken down. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                            removed: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{shortId}/reinstate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reverse an artifact takedown (Admin only). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The artifact was reinstated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                            removed: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/{id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss a report without taking the artifact down (Admin only). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The report was dismissed. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{shortId}/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List an artifact's proposals (optionally filtered by state). */
        get: {
            parameters: {
                query?: {
                    state?: "open" | "approved" | "changes_requested" | "withdrawn";
                };
                header?: never;
                path: {
                    shortId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The artifact's proposals. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            proposals: components["schemas"]["Proposal"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Propose a candidate version (multipart, like publish). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The created proposal, plus the thread ids it marked addressed. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Proposal"] & {
                            addressed: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{shortId}/proposals/{proposalId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One proposal, with a line diff against its base version. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortId: string;
                    proposalId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The proposal, with its diff. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Proposal"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{shortId}/proposals/{proposalId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a proposal (its content goes live as a new version). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortId: string;
                    proposalId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The approved proposal + the version number it became. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Proposal"] & {
                            published: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{shortId}/proposals/{proposalId}/request-changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request changes on a proposal (it stays open for revision). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortId: string;
                    proposalId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The proposal, now changes_requested. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Proposal"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{shortId}/proposals/{proposalId}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Withdraw an open proposal (proposer or a manager). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortId: string;
                    proposalId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The proposal, now withdrawn. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Proposal"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{shortId}/review/send-back": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send back a review with the human's answers. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The round, now sent_back. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            round: components["schemas"]["ReviewRound"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{shortId}/review/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a review (the go-signal). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The round, now approved. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            round: components["schemas"]["ReviewRound"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{shortId}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List an artifact's review rounds and the pending one, if any. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All rounds (newest first) and the current pending round or null. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            rounds: components["schemas"]["ReviewRound"][];
                            pending: components["schemas"]["ReviewRound"] & unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{shortId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List an artifact's comments (authenticated readers only). */
        get: {
            parameters: {
                query?: {
                    state?: "open" | "resolved" | "outdated" | "addressed";
                };
                header?: never;
                path: {
                    shortId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The artifact's comments, each flagged whether its anchor still resolves. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            comments: components["schemas"]["Comment"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Post a comment (new thread) or a reply (with thread_id). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The created comment. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comment"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{shortId}/comments/{commentId}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve or reopen the thread a comment belongs to. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortId: string;
                    commentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The thread's new state. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            thread_id: string;
                            /** @enum {string} */
                            state: "open" | "resolved";
                            updated: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{shortId}/comments/{commentId}/react": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggle a reaction on a comment. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortId: string;
                    commentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The updated comment. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comment"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{shortId}/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Soft-delete a comment (author only); the row stays, body tombstoned. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortId: string;
                    commentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The tombstoned comment. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comment"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Edit a comment's body (author only). */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortId: string;
                    commentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The edited comment. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comment"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/contexts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the workspace's contexts. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The workspace's contexts. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            contexts: components["schemas"]["ContextInfo"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a context (wire an agent to a manifest artifact). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The created context. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ContextInfo"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contexts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One context; the context's agent also gets the manifest source to run. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The context (with manifest source for the agent). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ContextInfo"] & {
                            manifest_version?: number;
                            manifest_md?: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a context (its creator or a workspace manager). */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The context was deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contexts/{id}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A context's sessions (owner sees all; others only their own). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The sessions. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            sessions: components["schemas"]["Session"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Ask: open a session with the first question. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The new session and its first message. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            session: components["schemas"]["Session"];
                            messages: components["schemas"]["SessionMessage"][];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One session with its transcript (asker or context owner). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The session, its context, and the full transcript. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            session: components["schemas"]["Session"];
                            context: {
                                id: string;
                                name: string;
                            };
                            messages: components["schemas"]["SessionMessage"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Close a session (asker/owner) or fail it (the context's agent). */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The updated session. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            session: components["schemas"]["Session"];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/sessions/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Append a message to a session (asker follow-up or the agent's answer). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The appended message. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: components["schemas"]["SessionMessage"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contexts/{id}/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The runner's queue: open sessions with transcripts (agent bearer). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Open sessions, oldest first, each with its transcript. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            sessions: (components["schemas"]["Session"] & {
                                messages: components["schemas"]["SessionMessage"][];
                            })[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{shortId}/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a view of an artifact (de-duped; owner self-views excluded). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recorded (or skipped as a dup / self-view / disabled). */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{shortId}/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** View stats for an artifact (collaborators only). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Totals, per-version + daily counts, and recent distinct viewers. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Analytics"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the signed-in user's recent notifications and unread count. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The 50 most recent notifications and the current unread count. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            notifications: components["schemas"]["Notification"][];
                            unread: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notifications/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark notifications read (all, or a set of ids); returns the new unread count. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The unread count after marking. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            unread: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the workspace's webhooks (Admin only). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The workspace's webhooks, without their signing secrets. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            webhooks: components["schemas"]["Webhook"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a webhook (Admin only). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The created webhook, without its signing secret. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Webhook"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a webhook (Admin only). */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The webhook was deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/{id}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent delivery attempts for a webhook (Admin only). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The 20 most recent delivery attempts. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            deliveries: components["schemas"]["Delivery"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a sample event to a webhook so you can confirm it lands (Admin only). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The sample delivery was queued. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            queued: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{shortId}/domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List an artifact's subdomains + the workspace domains it's reachable at. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The subdomain base, the artifact's subdomains, and workspace domains. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            base: string | null;
                            domains: components["schemas"]["ArtifactDomain"][];
                            workspace_domains: {
                                host: string;
                                url: string;
                            }[];
                        };
                    };
                };
            };
        };
        /** Claim a vanity subdomain for the artifact. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The subdomain (already claimed by this artifact). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArtifactDomain"];
                    };
                };
                /** @description The newly claimed subdomain. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArtifactDomain"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{shortId}/domains/{host}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Release one of the artifact's subdomains. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortId: string;
                    host: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The subdomain was released. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspace/domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the workspace's custom domains and whether they're supported here. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Whether custom domains are enabled, the CNAME target, and the domains. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            enabled: boolean;
                            cname_target: string | null;
                            domains: components["schemas"]["WorkspaceDomain"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Attach a custom domain to the workspace. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The domain (already attached to this workspace). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceDomain"] & {
                            cname_target: string;
                        };
                    };
                };
                /** @description The newly attached domain, pending DNS validation. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceDomain"] & {
                            cname_target: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspace/domains/{host}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-check a custom domain's validation status. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    host: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The domain's current status. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceDomain"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspace/domains/{host}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Detach a custom domain from the workspace. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    host: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The domain was detached. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PublicProfile: {
            username: string;
            name: string | null;
            image: string | null;
            profession?: string | null;
            about?: string | null;
            github_login?: string | null;
            stats?: {
                works: number;
                followers: number;
                following: number;
            };
            followed_by_me?: boolean;
        };
        DirUser: {
            id: string;
            name: string | null;
            handle: string | null;
            /** @enum {string} */
            kind?: "user" | "agent";
            profession?: string | null;
        };
        Agent: {
            id: string;
            name: string;
            /** @enum {string} */
            role: "viewer" | "commenter" | "editor" | "owner";
            created_at: string;
        };
        ConnectedAgent: {
            clientId: string;
            clientName: string;
            scopes: string[];
            grantedAt: string;
        };
        ArtifactMember: {
            user_id: string;
            handle: string | null;
            name: string | null;
            profession?: string | null;
            /** @enum {string} */
            role: "viewer" | "commenter" | "editor" | "owner";
        };
        Follow: {
            id: string;
            org_id: string;
            user_id: string;
            /** @enum {string} */
            kind: "author" | "path" | "user";
            target: string;
            created_at: string;
            handle?: string | null;
            name?: string | null;
            image?: string | null;
        };
        Collection: {
            id: string;
            title: string;
            created_by: string;
            created_at: string;
            count: number;
            /** @enum {string} */
            kind?: "manual" | "repo" | "pr";
            parentId?: string;
            prNumber?: number;
            repo?: string;
        };
        SlackStatus: {
            available: boolean;
            connected: boolean;
            team_name: string | null;
            default_channel: string | null;
        };
        Report: {
            id: string;
            artifact_id: string;
            artifact_short_id: string;
            reason: string;
            detail: string | null;
            reporter: string | null;
            /** @enum {string} */
            state: "open" | "actioned" | "dismissed";
            created_at: string;
        };
        AuditEntry: {
            id: string;
            org_id: string;
            action: string;
            artifact_id: string | null;
            actor: string;
            detail: string | null;
            created_at: string;
        };
        DiffOp: {
            /** @enum {string} */
            t: "ctx" | "add" | "del";
            line: string;
        };
        Proposal: {
            id: string;
            /** @enum {string} */
            state: "open" | "approved" | "changes_requested" | "withdrawn";
            author: string;
            on_behalf_of?: {
                handle: string | null;
                name: string | null;
            } | null;
            message: string | null;
            base_version: number;
            /** @enum {string} */
            kind: "file" | "bundle";
            decided_by: string | null;
            decided_version: number | null;
            decision_note: string | null;
            decided_at: string | null;
            created_at: string;
            preview_url: string;
            diff?: {
                base_version: number;
                ops: components["schemas"]["DiffOp"][];
            };
        };
        ReviewRound: {
            id: string;
            artifact_id: string;
            version: number;
            requested_by: string;
            requested_for: string;
            /** @enum {string} */
            state: "pending" | "sent_back" | "approved";
            note: string | null;
            created_at: string;
            resolved_at: string | null;
        };
        Comment: {
            id: string;
            thread_id: string;
            base_version: number;
            path: string | null;
            anchor: string | null;
            body_md: string;
            author: string;
            /** @enum {string} */
            state: "open" | "addressed" | "resolved" | "outdated";
            created_at: string;
            anchored?: boolean;
            reactions?: {
                [key: string]: string[];
            };
            edited?: boolean;
            edited_at?: string | null;
            deleted?: boolean;
            mentions?: components["schemas"]["Mention"][];
        };
        Mention: {
            id: string;
            name: string;
        };
        ContextInfo: {
            id: string;
            name: string;
            agent_id: string;
            manifest_short_id: string | null;
            created_by: string;
            created_at: string;
        };
        Session: {
            id: string;
            context_id: string;
            asker_id: string;
            context_version: number;
            /** @enum {string} */
            state: "open" | "answered" | "escalated" | "failed" | "closed";
            created_at: string;
            updated_at: string;
        };
        SessionMessage: {
            id: string;
            /** @enum {string} */
            author_kind: "asker" | "agent";
            author_id: string;
            body_md: string;
            meta: components["schemas"]["SessionMeta"];
            created_at: string;
        };
        SessionMeta: {
            query?: string | null;
            confidence?: number | null;
            caveats?: string[];
            escalation_reason?: string | null;
            artifacts?: {
                short_id: string;
                title: string;
            }[];
        } | null;
        Analytics: {
            total: number;
            unique: number;
            anonViewers: number;
            perVersion: {
                version: number;
                count: number;
            }[];
            daily: {
                day: string;
                count: number;
            }[];
            recent: {
                viewer: string;
                /** @enum {string} */
                kind: "user" | "anon";
                at: string;
                avatar?: string | null;
            }[];
        };
        Notification: {
            id: string;
            user_id: string;
            actor: string;
            /** @enum {string} */
            kind: "mention" | "comment" | "share" | "follow" | "publish" | "review";
            artifact_id: string;
            artifact_short_id: string;
            artifact_title: string | null;
            thread_id: string;
            comment_id: string;
            preview: string;
            read: 0 | 1;
            created_at: string;
        };
        Webhook: {
            id: string;
            artifact_id: string | null;
            url: string;
            /** @enum {string} */
            kind: "generic" | "slack";
            events: string;
            label: string | null;
            active: 0 | 1;
            created_at: string;
        };
        Delivery: {
            id: string;
            event_type: string;
            /** @enum {string} */
            status: "pending" | "delivered" | "dead";
            attempts: number;
            last_error: string | null;
            created_at: string;
        };
        ArtifactDomain: {
            host: string;
            url: string;
            kind: string;
            status: string;
            created_at: string;
        };
        WorkspaceDomain: {
            host: string;
            status: string;
            records?: components["schemas"]["DomainDnsRecord"][];
            created_at: string;
        };
        DomainDnsRecord: {
            type: string;
            name: string;
            value: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
