/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as UnlistedRouteImport } from './routes/unlisted'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as SharedRouteImport } from './routes/shared'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as NewRouteImport } from './routes/new'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BrandprintRouteImport } from './routes/brandprint'
import { Route as ArchivedRouteImport } from './routes/archived'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates.index'
import { Route as TemplateLibrariesIndexRouteImport } from './routes/template-libraries.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as ContextsIndexRouteImport } from './routes/contexts.index'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as UsersHandleRouteImport } from './routes/users.$handle'
import { Route as TemplatesRefRouteImport } from './routes/templates.$ref'
import { Route as TemplateLibrariesIdRouteImport } from './routes/template-libraries.$id'
import { Route as SettingsSectionRouteImport } from './routes/settings.$section'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ContextsNewRouteImport } from './routes/contexts.new'
import { Route as ContextsIdRouteImport } from './routes/contexts.$id'
import { Route as CollectionsIdRouteImport } from './routes/collections.$id'
import { Route as ClaimTokenRouteImport } from './routes/claim.$token'
import { Route as ArtifactsRefRouteImport } from './routes/artifacts.$ref'
import { Route as AgentsNewRouteImport } from './routes/agents.new'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'
import { Route as InviteCTokenRouteImport } from './routes/invite.c.$token'
import { Route as InviteATokenRouteImport } from './routes/invite.a.$token'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlistedRoute = UnlistedRouteImport.update({
  id: '/unlisted',
  path: '/unlisted',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedRoute = SharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandprintRoute = BrandprintRouteImport.update({
  id: '/brandprint',
  path: '/brandprint',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivedRoute = ArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateLibrariesIndexRoute = TemplateLibrariesIndexRouteImport.update({
  id: '/template-libraries/',
  path: '/template-libraries/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ContextsIndexRoute = ContextsIndexRouteImport.update({
  id: '/contexts/',
  path: '/contexts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersHandleRoute = UsersHandleRouteImport.update({
  id: '/users/$handle',
  path: '/users/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRefRoute = TemplatesRefRouteImport.update({
  id: '/templates/$ref',
  path: '/templates/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateLibrariesIdRoute = TemplateLibrariesIdRouteImport.update({
  id: '/template-libraries/$id',
  path: '/template-libraries/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSectionRoute = SettingsSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => SettingsRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextsNewRoute = ContextsNewRouteImport.update({
  id: '/contexts/new',
  path: '/contexts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextsIdRoute = ContextsIdRouteImport.update({
  id: '/contexts/$id',
  path: '/contexts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIdRoute = CollectionsIdRouteImport.update({
  id: '/collections/$id',
  path: '/collections/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimTokenRoute = ClaimTokenRouteImport.update({
  id: '/claim/$token',
  path: '/claim/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRefRoute = ArtifactsRefRouteImport.update({
  id: '/artifacts/$ref',
  path: '/artifacts/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsNewRoute = AgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/agents/$id',
  path: '/agents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteCTokenRoute = InviteCTokenRouteImport.update({
  id: '/invite/c/$token',
  path: '/invite/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteATokenRoute = InviteATokenRouteImport.update({
  id: '/invite/a/$token',
  path: '/invite/a/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/archived': typeof ArchivedRoute
  '/brandprint': typeof BrandprintRoute
  '/chat': typeof ChatRoute
  '/favorites': typeof FavoritesRoute
  '/feedback': typeof FeedbackRoute
  '/following': typeof FollowingRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/people': typeof PeopleRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/shared': typeof SharedRoute
  '/showcase': typeof ShowcaseRoute
  '/skills': typeof SkillsRoute
  '/unlisted': typeof UnlistedRoute
  '/welcome': typeof WelcomeRoute
  '/workflows': typeof WorkflowsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/artifacts/$ref': typeof ArtifactsRefRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/contexts/$id': typeof ContextsIdRoute
  '/contexts/new': typeof ContextsNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/template-libraries/$id': typeof TemplateLibrariesIdRoute
  '/templates/$ref': typeof TemplatesRefRoute
  '/users/$handle': typeof UsersHandleRoute
  '/agents/': typeof AgentsIndexRoute
  '/contexts/': typeof ContextsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/template-libraries/': typeof TemplateLibrariesIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/invite/a/$token': typeof InviteATokenRoute
  '/invite/c/$token': typeof InviteCTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/archived': typeof ArchivedRoute
  '/brandprint': typeof BrandprintRoute
  '/chat': typeof ChatRoute
  '/favorites': typeof FavoritesRoute
  '/feedback': typeof FeedbackRoute
  '/following': typeof FollowingRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/people': typeof PeopleRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/search': typeof SearchRoute
  '/shared': typeof SharedRoute
  '/showcase': typeof ShowcaseRoute
  '/skills': typeof SkillsRoute
  '/unlisted': typeof UnlistedRoute
  '/welcome': typeof WelcomeRoute
  '/workflows': typeof WorkflowsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/artifacts/$ref': typeof ArtifactsRefRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/contexts/$id': typeof ContextsIdRoute
  '/contexts/new': typeof ContextsNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/template-libraries/$id': typeof TemplateLibrariesIdRoute
  '/templates/$ref': typeof TemplatesRefRoute
  '/users/$handle': typeof UsersHandleRoute
  '/agents': typeof AgentsIndexRoute
  '/contexts': typeof ContextsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/template-libraries': typeof TemplateLibrariesIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/invite/a/$token': typeof InviteATokenRoute
  '/invite/c/$token': typeof InviteCTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/archived': typeof ArchivedRoute
  '/brandprint': typeof BrandprintRoute
  '/chat': typeof ChatRoute
  '/favorites': typeof FavoritesRoute
  '/feedback': typeof FeedbackRoute
  '/following': typeof FollowingRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/people': typeof PeopleRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/shared': typeof SharedRoute
  '/showcase': typeof ShowcaseRoute
  '/skills': typeof SkillsRoute
  '/unlisted': typeof UnlistedRoute
  '/welcome': typeof WelcomeRoute
  '/workflows': typeof WorkflowsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/artifacts/$ref': typeof ArtifactsRefRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/contexts/$id': typeof ContextsIdRoute
  '/contexts/new': typeof ContextsNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/template-libraries/$id': typeof TemplateLibrariesIdRoute
  '/templates/$ref': typeof TemplatesRefRoute
  '/users/$handle': typeof UsersHandleRoute
  '/agents/': typeof AgentsIndexRoute
  '/contexts/': typeof ContextsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/template-libraries/': typeof TemplateLibrariesIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/invite/a/$token': typeof InviteATokenRoute
  '/invite/c/$token': typeof InviteCTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/archived'
    | '/brandprint'
    | '/chat'
    | '/favorites'
    | '/feedback'
    | '/following'
    | '/login'
    | '/new'
    | '/people'
    | '/reset-password'
    | '/roadmap'
    | '/search'
    | '/settings'
    | '/shared'
    | '/showcase'
    | '/skills'
    | '/unlisted'
    | '/welcome'
    | '/workflows'
    | '/agents/$id'
    | '/agents/new'
    | '/artifacts/$ref'
    | '/claim/$token'
    | '/collections/$id'
    | '/contexts/$id'
    | '/contexts/new'
    | '/invite/$token'
    | '/settings/$section'
    | '/template-libraries/$id'
    | '/templates/$ref'
    | '/users/$handle'
    | '/agents/'
    | '/contexts/'
    | '/settings/'
    | '/template-libraries/'
    | '/templates/'
    | '/invite/a/$token'
    | '/invite/c/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/archived'
    | '/brandprint'
    | '/chat'
    | '/favorites'
    | '/feedback'
    | '/following'
    | '/login'
    | '/new'
    | '/people'
    | '/reset-password'
    | '/roadmap'
    | '/search'
    | '/shared'
    | '/showcase'
    | '/skills'
    | '/unlisted'
    | '/welcome'
    | '/workflows'
    | '/agents/$id'
    | '/agents/new'
    | '/artifacts/$ref'
    | '/claim/$token'
    | '/collections/$id'
    | '/contexts/$id'
    | '/contexts/new'
    | '/invite/$token'
    | '/settings/$section'
    | '/template-libraries/$id'
    | '/templates/$ref'
    | '/users/$handle'
    | '/agents'
    | '/contexts'
    | '/settings'
    | '/template-libraries'
    | '/templates'
    | '/invite/a/$token'
    | '/invite/c/$token'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/archived'
    | '/brandprint'
    | '/chat'
    | '/favorites'
    | '/feedback'
    | '/following'
    | '/login'
    | '/new'
    | '/people'
    | '/reset-password'
    | '/roadmap'
    | '/search'
    | '/settings'
    | '/shared'
    | '/showcase'
    | '/skills'
    | '/unlisted'
    | '/welcome'
    | '/workflows'
    | '/agents/$id'
    | '/agents/new'
    | '/artifacts/$ref'
    | '/claim/$token'
    | '/collections/$id'
    | '/contexts/$id'
    | '/contexts/new'
    | '/invite/$token'
    | '/settings/$section'
    | '/template-libraries/$id'
    | '/templates/$ref'
    | '/users/$handle'
    | '/agents/'
    | '/contexts/'
    | '/settings/'
    | '/template-libraries/'
    | '/templates/'
    | '/invite/a/$token'
    | '/invite/c/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  ArchivedRoute: typeof ArchivedRoute
  BrandprintRoute: typeof BrandprintRoute
  ChatRoute: typeof ChatRoute
  FavoritesRoute: typeof FavoritesRoute
  FeedbackRoute: typeof FeedbackRoute
  FollowingRoute: typeof FollowingRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  PeopleRoute: typeof PeopleRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoadmapRoute: typeof RoadmapRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SharedRoute: typeof SharedRoute
  ShowcaseRoute: typeof ShowcaseRoute
  SkillsRoute: typeof SkillsRoute
  UnlistedRoute: typeof UnlistedRoute
  WelcomeRoute: typeof WelcomeRoute
  WorkflowsRoute: typeof WorkflowsRoute
  AgentsIdRoute: typeof AgentsIdRoute
  AgentsNewRoute: typeof AgentsNewRoute
  ArtifactsRefRoute: typeof ArtifactsRefRoute
  ClaimTokenRoute: typeof ClaimTokenRoute
  CollectionsIdRoute: typeof CollectionsIdRoute
  ContextsIdRoute: typeof ContextsIdRoute
  ContextsNewRoute: typeof ContextsNewRoute
  InviteTokenRoute: typeof InviteTokenRoute
  TemplateLibrariesIdRoute: typeof TemplateLibrariesIdRoute
  TemplatesRefRoute: typeof TemplatesRefRoute
  UsersHandleRoute: typeof UsersHandleRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  ContextsIndexRoute: typeof ContextsIndexRoute
  TemplateLibrariesIndexRoute: typeof TemplateLibrariesIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  InviteATokenRoute: typeof InviteATokenRoute
  InviteCTokenRoute: typeof InviteCTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlisted': {
      id: '/unlisted'
      path: '/unlisted'
      fullPath: '/unlisted'
      preLoaderRoute: typeof UnlistedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared': {
      id: '/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brandprint': {
      id: '/brandprint'
      path: '/brandprint'
      fullPath: '/brandprint'
      preLoaderRoute: typeof BrandprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archived': {
      id: '/archived'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof ArchivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template-libraries/': {
      id: '/template-libraries/'
      path: '/template-libraries'
      fullPath: '/template-libraries/'
      preLoaderRoute: typeof TemplateLibrariesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/contexts/': {
      id: '/contexts/'
      path: '/contexts'
      fullPath: '/contexts/'
      preLoaderRoute: typeof ContextsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$handle': {
      id: '/users/$handle'
      path: '/users/$handle'
      fullPath: '/users/$handle'
      preLoaderRoute: typeof UsersHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$ref': {
      id: '/templates/$ref'
      path: '/templates/$ref'
      fullPath: '/templates/$ref'
      preLoaderRoute: typeof TemplatesRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template-libraries/$id': {
      id: '/template-libraries/$id'
      path: '/template-libraries/$id'
      fullPath: '/template-libraries/$id'
      preLoaderRoute: typeof TemplateLibrariesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$section': {
      id: '/settings/$section'
      path: '/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof SettingsSectionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contexts/new': {
      id: '/contexts/new'
      path: '/contexts/new'
      fullPath: '/contexts/new'
      preLoaderRoute: typeof ContextsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contexts/$id': {
      id: '/contexts/$id'
      path: '/contexts/$id'
      fullPath: '/contexts/$id'
      preLoaderRoute: typeof ContextsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$id': {
      id: '/collections/$id'
      path: '/collections/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof CollectionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$token': {
      id: '/claim/$token'
      path: '/claim/$token'
      fullPath: '/claim/$token'
      preLoaderRoute: typeof ClaimTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts/$ref': {
      id: '/artifacts/$ref'
      path: '/artifacts/$ref'
      fullPath: '/artifacts/$ref'
      preLoaderRoute: typeof ArtifactsRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/new': {
      id: '/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AgentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/agents/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/c/$token': {
      id: '/invite/c/$token'
      path: '/invite/c/$token'
      fullPath: '/invite/c/$token'
      preLoaderRoute: typeof InviteCTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/a/$token': {
      id: '/invite/a/$token'
      path: '/invite/a/$token'
      fullPath: '/invite/a/$token'
      preLoaderRoute: typeof InviteATokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsSectionRoute: typeof SettingsSectionRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsSectionRoute: SettingsSectionRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  ArchivedRoute: ArchivedRoute,
  BrandprintRoute: BrandprintRoute,
  ChatRoute: ChatRoute,
  FavoritesRoute: FavoritesRoute,
  FeedbackRoute: FeedbackRoute,
  FollowingRoute: FollowingRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  PeopleRoute: PeopleRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoadmapRoute: RoadmapRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SharedRoute: SharedRoute,
  ShowcaseRoute: ShowcaseRoute,
  SkillsRoute: SkillsRoute,
  UnlistedRoute: UnlistedRoute,
  WelcomeRoute: WelcomeRoute,
  WorkflowsRoute: WorkflowsRoute,
  AgentsIdRoute: AgentsIdRoute,
  AgentsNewRoute: AgentsNewRoute,
  ArtifactsRefRoute: ArtifactsRefRoute,
  ClaimTokenRoute: ClaimTokenRoute,
  CollectionsIdRoute: CollectionsIdRoute,
  ContextsIdRoute: ContextsIdRoute,
  ContextsNewRoute: ContextsNewRoute,
  InviteTokenRoute: InviteTokenRoute,
  TemplateLibrariesIdRoute: TemplateLibrariesIdRoute,
  TemplatesRefRoute: TemplatesRefRoute,
  UsersHandleRoute: UsersHandleRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  ContextsIndexRoute: ContextsIndexRoute,
  TemplateLibrariesIndexRoute: TemplateLibrariesIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  InviteATokenRoute: InviteATokenRoute,
  InviteCTokenRoute: InviteCTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
