// GENERATED by scripts/gen-template-protocol-instruction.mjs — do not edit.
// Regenerate: pnpm gen:template-protocol-instruction

/** The shared preservation contract for every ordinary artifact-template handoff. */
export const TEMPLATE_PROTOCOL_INSTRUCTION = "Inspect the reference's authored facts and protocols before adapting it: for an artifact, call Derive read with `data:\"*\"`; for a template-library entry, inspect the exact starter source returned by read. Preserve every relevant authored fact. For each recognized Derive protocol — for example `derive-deck`, `bundle-manifest`, or `workflow-definition` — read its matching core skill and run that protocol's validation or Preview before publishing. Arbitrary facts do not imply a matching skill."
