import type { TemplateDefinition } from "../types"
import { input } from "./input"

export const AGENT_ARTIFACT_TEMPLATE_DEFINITIONS: readonly TemplateDefinition[] = [
  {
    id: "context-manifest",
    kind: "artifact",
    category: "Agent",
    format: "md",
    title: "Context manifest",
    defaultTitle: "Context manifest",
    description:
      "Purpose, sources, operating rules, tool expectations, publish behavior, and starter prompts.",
    outcome: "Make an agent setup understandable before it acts.",
    sections: [
      "Purpose",
      "What this context knows",
      "Operating rules",
      "Tools",
      "Publishing",
      "Boundaries",
      "Starter prompts",
    ],
    inputs: [
      input("Job", "What should this context make easier?", true),
      input("Sources", "What should it know?"),
      input("Boundaries", "What must it not do?"),
    ],
    tags: ["context", "agent", "manifest"],
  },
  {
    id: "skill-package",
    kind: "artifact",
    category: "Agent",
    format: "md",
    title: "Skill package",
    defaultTitle: "Skill package",
    description:
      "Trigger, inputs, procedure, safety boundaries, output contract, examples, and verification.",
    outcome: "Turn expert practice into a procedure an agent can use reliably.",
    sections: [
      "When to use",
      "Inputs",
      "Procedure",
      "Safety",
      "Output contract",
      "Examples",
      "Verification",
    ],
    inputs: [
      input("Capability", "What should the skill enable?", true),
      input("Triggers", "When should an agent reach for it?"),
      input("Examples", "Representative successful cases"),
    ],
    tags: ["skill", "agent", "procedure"],
  },
  {
    id: "review-rubric",
    kind: "artifact",
    category: "Agent",
    format: "md",
    title: "Review rubric",
    defaultTitle: "Review rubric",
    description:
      "Criteria, severity, evidence requirements, pass conditions, and a concise response format.",
    outcome: "Make automated and human review consistent without hiding judgment.",
    sections: [
      "Purpose",
      "Criteria",
      "Severity",
      "Evidence",
      "Pass conditions",
      "Response format",
      "Examples",
    ],
    inputs: [
      input("Subject", "What is being reviewed?", true),
      input("Standards", "Policies or examples to apply"),
      input("Audience", "Who receives the findings?"),
    ],
    tags: ["review", "quality", "agent"],
  },
  {
    id: "automation-brief",
    kind: "artifact",
    category: "Agent",
    format: "md",
    title: "Automation brief",
    defaultTitle: "Automation brief",
    description:
      "Trigger, instruction, sources, expected outputs, failure handling, approvals, and observability.",
    outcome: "Specify recurring agent work so its behavior can be reviewed before it runs.",
    sections: [
      "Outcome",
      "Trigger",
      "Instruction",
      "Sources",
      "Output",
      "Approvals",
      "Failure handling",
      "Observability",
    ],
    inputs: [
      input("Job", "What repeats?", true),
      input("Trigger", "When should it run?", true),
      input("Authority", "What may it publish or change?"),
    ],
    tags: ["automation", "agent", "operations"],
  },
  {
    id: "source-guide",
    kind: "artifact",
    category: "Agent",
    format: "md",
    title: "Source guide",
    defaultTitle: "Source guide",
    description:
      "What a connected system contains, preferred tools, query patterns, caveats, and citation rules.",
    outcome: "Help an agent use a source accurately without relearning its edges each session.",
    sections: [
      "Source",
      "What it contains",
      "Preferred tools",
      "Query patterns",
      "Caveats",
      "Citation rules",
      "Examples",
    ],
    inputs: [
      input("System", "The connected source", true),
      input("Tools", "Available operations"),
      input("Caveats", "Known gaps or permission boundaries"),
    ],
    tags: ["source", "agent", "guide"],
  },
]
