import type { TemplateDefinition } from "../types"
import { input } from "./input"

export const CONTEXT_TEMPLATE_DEFINITIONS: readonly TemplateDefinition[] = [
  {
    id: "weekly-research-context",
    kind: "context",
    category: "Agent",
    format: "md",
    title: "Weekly research brief",
    defaultTitle: "Weekly research brief manifest",
    description:
      "Tracks a topic, reads approved sources, and proposes a cited weekly digest for review.",
    outcome: "Stay current on a changing question without rebuilding the research loop each week.",
    sections: [
      "Purpose",
      "Approved sources",
      "Weekly procedure",
      "Evidence rules",
      "Output",
      "Review policy",
      "Boundaries",
    ],
    inputs: [
      input("Topic", "The question or market to track", true),
      input("Sources", "Approved artifacts, tags, or connections", true),
      input("Cadence", "When the brief should be ready"),
    ],
    tags: ["research", "weekly", "context"],
    featured: true,
    starterPrompts: [
      "What changed this week?",
      "Show the evidence behind the top signal.",
      "Draft this week's research brief.",
    ],
  },
  {
    id: "product-decision-context",
    kind: "context",
    category: "Agent",
    format: "md",
    title: "Product decision partner",
    defaultTitle: "Product decision partner manifest",
    description:
      "Loads strategy and user evidence, pressure-tests options, and proposes durable decision memos.",
    outcome: "Keep product judgment connected to evidence and prior choices.",
    sections: [
      "Purpose",
      "Strategy sources",
      "Evidence",
      "Decision method",
      "Output",
      "Review behavior",
      "Boundaries",
    ],
    inputs: [
      input("Strategy", "The strategy artifacts to hold constant", true),
      input("Evidence", "Research and product sources"),
      input("Authority", "Proposal-only or publish"),
    ],
    tags: ["product", "decision", "context"],
    starterPrompts: [
      "Pressure-test these options.",
      "What prior decisions constrain this?",
      "Propose a decision memo.",
    ],
  },
  {
    id: "customer-room-context",
    kind: "context",
    category: "Agent",
    format: "md",
    title: "Customer account room",
    defaultTitle: "Customer account room manifest",
    description:
      "Combines notes, usage, stakeholders, and commitments into a conservative living account view.",
    outcome: "Give the account team shared memory without flattening sensitive context.",
    sections: [
      "Purpose",
      "Account sources",
      "Stakeholder handling",
      "Health method",
      "Outputs",
      "Access",
      "Boundaries",
    ],
    inputs: [
      input("Account", "Customer or partner", true),
      input("Sources", "Notes, usage, and commitments", true),
      input("Sensitivity", "Special access constraints"),
    ],
    tags: ["customer", "account", "context"],
    starterPrompts: [
      "What changed in this account?",
      "Where are commitments at risk?",
      "Draft the next account review.",
    ],
  },
  {
    id: "launch-steward-context",
    kind: "context",
    category: "Agent",
    format: "md",
    title: "Launch steward",
    defaultTitle: "Launch steward manifest",
    description:
      "Tracks launch artifacts and milestones, catches drift, and proposes a weekly status revision.",
    outcome: "Keep a cross-functional launch coherent as the facts move.",
    sections: [
      "Purpose",
      "Launch sources",
      "Checks",
      "Update cadence",
      "Escalation",
      "Output",
      "Boundaries",
    ],
    inputs: [
      input("Launch", "The launch being stewarded", true),
      input("Plan", "The canonical launch plan", true),
      input("Signals", "Artifacts or systems that show progress"),
    ],
    tags: ["launch", "program", "context"],
    starterPrompts: [
      "What drifted since the last update?",
      "Which milestone is least credible?",
      "Propose this week's launch status.",
    ],
  },
  {
    id: "repository-guide-context",
    kind: "context",
    category: "Agent",
    format: "md",
    title: "Repository guide",
    defaultTitle: "Repository guide manifest",
    description:
      "Packages architecture, contribution rules, and review expectations for coding agents.",
    outcome: "Let coding agents begin with the repository's actual operating rules.",
    sections: [
      "Purpose",
      "Repository map",
      "Architecture",
      "Working rules",
      "Verification",
      "Review",
      "Boundaries",
    ],
    inputs: [
      input("Repository", "The codebase this context supports", true),
      input("Rules", "Contribution and verification artifacts"),
      input("Sources", "Architecture and product references"),
    ],
    tags: ["engineering", "repository", "context"],
    starterPrompts: [
      "Orient me to this repository.",
      "Which checks govern this change?",
      "Review this plan against the architecture.",
    ],
  },
  {
    id: "brand-guardian-context",
    kind: "context",
    category: "Agent",
    format: "md",
    title: "Brand guardian",
    defaultTitle: "Brand guardian manifest",
    description:
      "Loads Brandprint and approved assets, reviews outputs, and proposes a compatible visual direction.",
    outcome: "Make brand guidance useful at creation time without turning it into a gatekeeper.",
    sections: [
      "Purpose",
      "Brandprint",
      "Approved assets",
      "Review method",
      "Visual direction",
      "Output",
      "Boundaries",
    ],
    inputs: [
      input("Brandprint", "The workspace's brand profile", true),
      input("Assets", "Approved logos, imagery, or examples"),
      input("Strictness", "Advisory or approval-required"),
    ],
    tags: ["brand", "review", "context"],
    starterPrompts: [
      "Review this against our Brandprint.",
      "Propose a visual direction for this artifact.",
      "What is off-brand, and why?",
    ],
  },
]
