import type { TemplateDefinition } from "../types"
import { input } from "./input"

export const DECK_TEMPLATE_DEFINITIONS: readonly TemplateDefinition[] = [
  {
    id: "narrative-pitch",
    kind: "artifact",
    category: "Deck",
    format: "html",
    title: "Narrative pitch",
    defaultTitle: "Narrative pitch",
    description:
      "Explain what changed, why it matters, what you built, and what should happen next.",
    outcome: "Give the audience a clear reason to act.",
    sections: ["The change", "The tension", "The insight", "The product", "The proof", "The plan"],
    inputs: [
      input("Audience", "Who needs to believe this?", true),
      input("Objective", "What should they do next?", true),
      input("Evidence", "Artifacts or facts that support the story"),
    ],
    tags: ["pitch", "story", "deck"],
    featured: true,
  },
  {
    id: "seed-fundraising",
    kind: "artifact",
    category: "Deck",
    format: "html",
    title: "Seed fundraising",
    defaultTitle: "Seed round",
    description: "Present the problem, product, market, traction, team, and funding request.",
    outcome: "Help investors understand the opportunity and the funding request.",
    sections: ["Why now", "The wedge", "Product", "Market", "Traction", "Model", "Team", "The ask"],
    inputs: [
      input("Company", "Company or project name", true),
      input("Round", "Target raise and use of funds"),
      input("Traction", "The evidence that deserves the room"),
    ],
    tags: ["fundraising", "founder", "deck"],
  },
  {
    id: "product-launch",
    kind: "artifact",
    category: "Deck",
    format: "html",
    title: "Product launch",
    defaultTitle: "Product launch",
    description:
      "Show who the launch is for, what changes, how it works, and when it is available.",
    outcome: "Help the audience understand the launch and what to do next.",
    sections: [
      "Audience",
      "Before",
      "Reveal",
      "How it works",
      "Why it matters",
      "Proof",
      "Availability",
    ],
    inputs: [
      input("Product", "What is launching?", true),
      input("Audience", "Who feels the change first?", true),
      input("Proof", "Demo, quote, or measurable result"),
    ],
    tags: ["launch", "marketing", "deck"],
  },
  {
    id: "quarterly-business-review",
    kind: "artifact",
    category: "Deck",
    format: "html",
    title: "Quarterly business review",
    defaultTitle: "Quarterly business review",
    description: "Review goals, results, drivers, risks, decisions, and next-quarter commitments.",
    outcome: "Agree on the decisions and commitments for the next quarter.",
    sections: [
      "Quarter in one page",
      "Scorecard",
      "Drivers",
      "Customers",
      "Risks",
      "Decisions",
      "Commitments",
    ],
    inputs: [
      input("Period", "Quarter or review window", true),
      input("Metrics", "The source of truth for the scorecard", true),
      input("Decisions", "Items that need a call"),
    ],
    tags: ["qbr", "operations", "deck"],
    featured: true,
  },
  {
    id: "research-briefing",
    kind: "artifact",
    category: "Deck",
    format: "html",
    title: "Research briefing",
    defaultTitle: "Research briefing",
    description: "Present the question, method, evidence, uncertainty, and recommendation.",
    outcome: "Help the audience understand the evidence and its practical effect.",
    sections: [
      "Question",
      "Method",
      "Signal",
      "Evidence",
      "Interpretation",
      "Uncertainty",
      "Recommendation",
    ],
    inputs: [
      input("Question", "The question this research answers", true),
      input("Sources", "Research artifacts or datasets", true),
      input("Audience", "Who will act on the answer?"),
    ],
    tags: ["research", "evidence", "deck"],
  },
  {
    id: "board-update",
    kind: "artifact",
    category: "Deck",
    format: "html",
    title: "Board update",
    defaultTitle: "Board update",
    description:
      "Summarize progress, finances, strategy, risks, and the decisions needed from the board.",
    outcome: "Give the board the context it needs to discuss decisions.",
    sections: [
      "Executive signal",
      "Progress",
      "Financial view",
      "Strategy",
      "Risks",
      "Board asks",
      "Appendix",
    ],
    inputs: [
      input("Period", "Reporting period", true),
      input("Plan", "The goals being measured against"),
      input("Asks", "Where the board can help"),
    ],
    tags: ["board", "executive", "deck"],
  },
]
