import type { TemplateDefinition } from "../types"
import { input } from "./input"

export const DECK_TEMPLATE_DEFINITIONS: readonly TemplateDefinition[] = [
  {
    id: "narrative-pitch",
    kind: "artifact",
    category: "Deck",
    format: "html",
    title: "Narrative pitch",
    defaultTitle: "Narrative pitch",
    description: "A spoken story that moves from a changing world to proof and a clear plan.",
    outcome: "Win belief before asking for action.",
    sections: ["The change", "The tension", "The insight", "The product", "The proof", "The plan"],
    inputs: [
      input("Audience", "Who needs to believe this?", true),
      input("Objective", "What should they do next?", true),
      input("Evidence", "Artifacts or facts that support the story"),
    ],
    tags: ["pitch", "story", "deck"],
    featured: true,
  },
  {
    id: "seed-fundraising",
    kind: "artifact",
    category: "Deck",
    format: "html",
    title: "Seed fundraising",
    defaultTitle: "Seed round",
    description:
      "A founder-led seed narrative with a sharp wedge, credible momentum, and a precise ask.",
    outcome: "Make the opportunity legible without sanding off the founder's point of view.",
    sections: ["Why now", "The wedge", "Product", "Market", "Traction", "Model", "Team", "The ask"],
    inputs: [
      input("Company", "Company or project name", true),
      input("Round", "Target raise and use of funds"),
      input("Traction", "The evidence that deserves the room"),
    ],
    tags: ["fundraising", "founder", "deck"],
  },
  {
    id: "product-launch",
    kind: "artifact",
    category: "Deck",
    format: "html",
    title: "Product launch",
    defaultTitle: "Product launch",
    description:
      "A reveal built around the audience's tension, the new capability, and the moment to act.",
    outcome: "Turn a feature announcement into a memorable change in the user's world.",
    sections: [
      "Audience",
      "Before",
      "Reveal",
      "How it works",
      "Why it matters",
      "Proof",
      "Availability",
    ],
    inputs: [
      input("Product", "What is launching?", true),
      input("Audience", "Who feels the change first?", true),
      input("Proof", "Demo, quote, or measurable result"),
    ],
    tags: ["launch", "marketing", "deck"],
  },
  {
    id: "quarterly-business-review",
    kind: "artifact",
    category: "Deck",
    format: "html",
    title: "Quarterly business review",
    defaultTitle: "Quarterly business review",
    description:
      "A decision-oriented review of goals, drivers, evidence, risks, and next-quarter commitments.",
    outcome: "Leave the room with shared signal and named commitments.",
    sections: [
      "Quarter in one page",
      "Scorecard",
      "Drivers",
      "Customers",
      "Risks",
      "Decisions",
      "Commitments",
    ],
    inputs: [
      input("Period", "Quarter or review window", true),
      input("Metrics", "The source of truth for the scorecard", true),
      input("Decisions", "Items that need a call"),
    ],
    tags: ["qbr", "operations", "deck"],
    featured: true,
  },
  {
    id: "research-briefing",
    kind: "artifact",
    category: "Deck",
    format: "html",
    title: "Research briefing",
    defaultTitle: "Research briefing",
    description:
      "Question, evidence, interpretation, uncertainty, and recommendation in a reviewable arc.",
    outcome: "Help a busy audience understand what the evidence changes.",
    sections: [
      "Question",
      "Method",
      "Signal",
      "Evidence",
      "Interpretation",
      "Uncertainty",
      "Recommendation",
    ],
    inputs: [
      input("Question", "The question this research answers", true),
      input("Sources", "Research artifacts or datasets", true),
      input("Audience", "Who will act on the answer?"),
    ],
    tags: ["research", "evidence", "deck"],
  },
  {
    id: "board-update",
    kind: "artifact",
    category: "Deck",
    format: "html",
    title: "Board update",
    defaultTitle: "Board update",
    description:
      "Executive signal first: progress, financial view, strategic risk, asks, and appendix.",
    outcome: "Use board time for judgment rather than narration.",
    sections: [
      "Executive signal",
      "Progress",
      "Financial view",
      "Strategy",
      "Risks",
      "Board asks",
      "Appendix",
    ],
    inputs: [
      input("Period", "Reporting period", true),
      input("Plan", "The goals being measured against"),
      input("Asks", "Where the board can help"),
    ],
    tags: ["board", "executive", "deck"],
  },
]
