import type { TemplateDefinition } from "../types"
import { input } from "./input"

export const DOC_TEMPLATE_DEFINITIONS: readonly TemplateDefinition[] = [
  {
    id: "decision-memo",
    kind: "artifact",
    category: "Doc",
    format: "md",
    title: "Decision memo",
    defaultTitle: "Decision memo",
    description: "Record a decision, the alternatives, the reasoning, and when to revisit it.",
    outcome: "Help readers understand the decision now and later.",
    sections: [
      "Decision",
      "Context",
      "Options considered",
      "Rationale",
      "Consequences",
      "Owners",
      "Revisit trigger",
    ],
    inputs: [
      input("Decision", "The choice being made", true),
      input("Owner", "Who is accountable?", true),
      input("Evidence", "Artifacts that support the choice"),
    ],
    tags: ["decision", "leadership", "doc"],
    featured: true,
  },
  {
    id: "product-brief",
    kind: "artifact",
    category: "Doc",
    format: "md",
    title: "Product brief",
    defaultTitle: "Product brief",
    description: "Define the problem, users, scope, requirements, risks, and measures of success.",
    outcome: "Give design and engineering the context needed to make implementation decisions.",
    sections: [
      "Problem",
      "Users",
      "Principles",
      "Experience",
      "Scope",
      "Requirements",
      "Risks",
      "Measures",
      "Open questions",
    ],
    inputs: [
      input("Problem", "What is failing today?", true),
      input("Users", "Who experiences it?", true),
      input("Evidence", "Research and product artifacts"),
    ],
    tags: ["product", "brief", "doc"],
  },
  {
    id: "technical-design",
    kind: "artifact",
    category: "Doc",
    format: "md",
    title: "Technical design",
    defaultTitle: "Technical design",
    description:
      "Explain the system, constraints, proposed design, failure modes, migration, and alternatives.",
    outcome: "Create a technical record that remains useful during and after implementation.",
    sections: [
      "Summary",
      "System context",
      "Constraints",
      "Proposal",
      "Data model",
      "Interfaces",
      "Failure modes",
      "Migration",
      "Observability",
      "Alternatives",
    ],
    inputs: [
      input("System", "The capability or boundary changing", true),
      input("Constraints", "Hard requirements and limits"),
      input("References", "Relevant code or architecture artifacts"),
    ],
    tags: ["engineering", "architecture", "doc"],
  },
  {
    id: "strategy-narrative",
    kind: "artifact",
    category: "Doc",
    format: "md",
    title: "Strategy narrative",
    defaultTitle: "Strategy narrative",
    description: "Describe the current situation, the main choice, the actions, and the tradeoffs.",
    outcome: "Make the strategy and its tradeoffs clear.",
    sections: [
      "Current reality",
      "Diagnosis",
      "Choice",
      "Coherent actions",
      "Capabilities",
      "Sequence",
      "Non-goals",
    ],
    inputs: [
      input("Arena", "Where the strategy applies", true),
      input("Evidence", "What makes the diagnosis credible"),
      input("Constraints", "What cannot be wished away"),
    ],
    tags: ["strategy", "leadership", "doc"],
  },
  {
    id: "launch-plan",
    kind: "artifact",
    category: "Doc",
    format: "md",
    title: "Launch plan",
    defaultTitle: "Launch plan",
    description:
      "Coordinate the audience, message, channels, assets, milestones, owners, and rollback plan.",
    outcome: "Give every launch owner the context and next action they need.",
    sections: [
      "Outcome",
      "Audience",
      "Positioning",
      "Channels",
      "Assets",
      "Milestones",
      "Owners",
      "Dependencies",
      "Rollback",
    ],
    inputs: [
      input("Launch", "What is going live?", true),
      input("Date", "Target window"),
      input("Owners", "Teams or individuals accountable"),
    ],
    tags: ["launch", "program", "doc"],
  },
  {
    id: "postmortem",
    kind: "artifact",
    category: "Doc",
    format: "md",
    title: "Postmortem",
    defaultTitle: "Postmortem",
    description:
      "Document the impact, timeline, contributing conditions, response, and corrective work.",
    outcome: "Capture what happened and how the team will prevent a repeat.",
    sections: [
      "Summary",
      "Impact",
      "Timeline",
      "Contributing conditions",
      "Response",
      "What worked",
      "What changes",
      "Verification",
    ],
    inputs: [
      input("Incident", "What happened?", true),
      input("Window", "Incident start and recovery"),
      input("Evidence", "Logs, messages, or related artifacts"),
    ],
    tags: ["incident", "learning", "doc"],
  },
  {
    id: "meeting-synthesis",
    kind: "artifact",
    category: "Doc",
    format: "md",
    title: "Meeting synthesis",
    defaultTitle: "Meeting synthesis",
    description:
      "Summarize the important points, decisions, disagreements, actions, and open questions.",
    outcome: "Give attendees and absent teammates a useful record of the meeting.",
    sections: [
      "Purpose",
      "Participants",
      "Signal",
      "Decisions",
      "Disagreements",
      "Actions",
      "Open questions",
    ],
    inputs: [
      input("Notes", "Transcript or raw notes", true),
      input("Purpose", "Why the meeting happened"),
      input("Audience", "Who needs the synthesis"),
    ],
    tags: ["meeting", "notes", "doc"],
  },
  {
    id: "research-plan",
    kind: "artifact",
    category: "Doc",
    format: "md",
    title: "Research plan",
    defaultTitle: "Research plan",
    description: "Define the question, hypotheses, sources, method, ethics, schedule, and outputs.",
    outcome: "Agree on how the research will answer the question.",
    sections: [
      "Question",
      "Hypotheses",
      "Participants or sources",
      "Method",
      "Analysis plan",
      "Ethics",
      "Schedule",
      "Outputs",
    ],
    inputs: [
      input("Question", "What must the work answer?", true),
      input("Decision", "What will the answer inform?"),
      input("Constraints", "Time, access, or ethical limits"),
    ],
    tags: ["research", "planning", "doc"],
  },
]
