import type { TemplateDefinition } from "../types"
import { input } from "./input"

export const DOC_TEMPLATE_DEFINITIONS: readonly TemplateDefinition[] = [
  {
    id: "decision-memo",
    kind: "artifact",
    category: "Doc",
    format: "md",
    title: "Decision memo",
    defaultTitle: "Decision memo",
    description:
      "A durable record of the call, the alternatives, the rationale, and the revisit trigger.",
    outcome: "Make a consequential choice easy to review now and understand later.",
    sections: [
      "Decision",
      "Context",
      "Options considered",
      "Rationale",
      "Consequences",
      "Owners",
      "Revisit trigger",
    ],
    inputs: [
      input("Decision", "The choice being made", true),
      input("Owner", "Who is accountable?", true),
      input("Evidence", "Artifacts that support the choice"),
    ],
    tags: ["decision", "leadership", "doc"],
    featured: true,
  },
  {
    id: "product-brief",
    kind: "artifact",
    category: "Doc",
    format: "md",
    title: "Product brief",
    defaultTitle: "Product brief",
    description: "Problem, users, principles, flows, scope, requirements, risks, and measures.",
    outcome: "Give design and engineering enough shared truth to make good local decisions.",
    sections: [
      "Problem",
      "Users",
      "Principles",
      "Experience",
      "Scope",
      "Requirements",
      "Risks",
      "Measures",
      "Open questions",
    ],
    inputs: [
      input("Problem", "What is failing today?", true),
      input("Users", "Who experiences it?", true),
      input("Evidence", "Research and product artifacts"),
    ],
    tags: ["product", "brief", "doc"],
  },
  {
    id: "technical-design",
    kind: "artifact",
    category: "Doc",
    format: "md",
    title: "Technical design",
    defaultTitle: "Technical design",
    description:
      "System context, constraints, proposal, data model, failure modes, migration, and alternatives.",
    outcome: "Create a technical record that survives the implementation.",
    sections: [
      "Summary",
      "System context",
      "Constraints",
      "Proposal",
      "Data model",
      "Interfaces",
      "Failure modes",
      "Migration",
      "Observability",
      "Alternatives",
    ],
    inputs: [
      input("System", "The capability or boundary changing", true),
      input("Constraints", "Hard requirements and limits"),
      input("References", "Relevant code or architecture artifacts"),
    ],
    tags: ["engineering", "architecture", "doc"],
  },
  {
    id: "strategy-narrative",
    kind: "artifact",
    category: "Doc",
    format: "md",
    title: "Strategy narrative",
    defaultTitle: "Strategy narrative",
    description: "A diagnosis, an explicit choice, and coherent actions—not a list of ambitions.",
    outcome: "Make the tradeoff at the heart of the strategy impossible to miss.",
    sections: [
      "Current reality",
      "Diagnosis",
      "Choice",
      "Coherent actions",
      "Capabilities",
      "Sequence",
      "Non-goals",
    ],
    inputs: [
      input("Arena", "Where the strategy applies", true),
      input("Evidence", "What makes the diagnosis credible"),
      input("Constraints", "What cannot be wished away"),
    ],
    tags: ["strategy", "leadership", "doc"],
  },
  {
    id: "launch-plan",
    kind: "artifact",
    category: "Doc",
    format: "md",
    title: "Launch plan",
    defaultTitle: "Launch plan",
    description:
      "Audience, position, channels, assets, milestones, owners, dependencies, and rollback.",
    outcome: "Coordinate a launch without turning the plan into a task dump.",
    sections: [
      "Outcome",
      "Audience",
      "Positioning",
      "Channels",
      "Assets",
      "Milestones",
      "Owners",
      "Dependencies",
      "Rollback",
    ],
    inputs: [
      input("Launch", "What is going live?", true),
      input("Date", "Target window"),
      input("Owners", "Teams or individuals accountable"),
    ],
    tags: ["launch", "program", "doc"],
  },
  {
    id: "postmortem",
    kind: "artifact",
    category: "Doc",
    format: "md",
    title: "Postmortem",
    defaultTitle: "Postmortem",
    description:
      "Impact, timeline, contributing conditions, response, learning, and verified corrective action.",
    outcome: "Learn without blame and close the loop on corrective work.",
    sections: [
      "Summary",
      "Impact",
      "Timeline",
      "Contributing conditions",
      "Response",
      "What worked",
      "What changes",
      "Verification",
    ],
    inputs: [
      input("Incident", "What happened?", true),
      input("Window", "Incident start and recovery"),
      input("Evidence", "Logs, messages, or related artifacts"),
    ],
    tags: ["incident", "learning", "doc"],
  },
  {
    id: "meeting-synthesis",
    kind: "artifact",
    category: "Doc",
    format: "md",
    title: "Meeting synthesis",
    defaultTitle: "Meeting synthesis",
    description:
      "Signal, decisions, disagreements, actions, and unresolved questions—without transcript theater.",
    outcome: "Turn a meeting into a compact piece of shared memory.",
    sections: [
      "Purpose",
      "Participants",
      "Signal",
      "Decisions",
      "Disagreements",
      "Actions",
      "Open questions",
    ],
    inputs: [
      input("Notes", "Transcript or raw notes", true),
      input("Purpose", "Why the meeting happened"),
      input("Audience", "Who needs the synthesis"),
    ],
    tags: ["meeting", "notes", "doc"],
  },
  {
    id: "research-plan",
    kind: "artifact",
    category: "Doc",
    format: "md",
    title: "Research plan",
    defaultTitle: "Research plan",
    description:
      "Question, hypotheses, sources, method, analysis, ethics, schedule, and output contract.",
    outcome: "Align on how evidence will be gathered before the first interview or query.",
    sections: [
      "Question",
      "Hypotheses",
      "Participants or sources",
      "Method",
      "Analysis plan",
      "Ethics",
      "Schedule",
      "Outputs",
    ],
    inputs: [
      input("Question", "What must the work answer?", true),
      input("Decision", "What will the answer inform?"),
      input("Constraints", "Time, access, or ethical limits"),
    ],
    tags: ["research", "planning", "doc"],
  },
]
