import type { TemplateDefinition } from "../types"
import { input } from "./input"

export const REPORT_SITE_AGENT_TEMPLATE_DEFINITIONS: readonly TemplateDefinition[] = [
  {
    id: "weekly-operating-review",
    kind: "artifact",
    category: "Report",
    format: "md",
    title: "Weekly operating review",
    defaultTitle: "Weekly operating review",
    description:
      "What changed, leading indicators, blockers, decisions, commitments, and owner follow-through.",
    outcome: "Run the week from deltas and decisions, not status narration.",
    sections: [
      "Week in one line",
      "What changed",
      "Leading indicators",
      "Blockers",
      "Decisions",
      "Commitments",
      "Carry-over",
    ],
    inputs: [
      input("Week", "Reporting week", true),
      input("Metrics", "Current operating signal"),
      input("Prior review", "Last week's commitments"),
    ],
    tags: ["weekly", "operations", "report"],
  },
  {
    id: "customer-health-report",
    kind: "artifact",
    category: "Report",
    format: "md",
    title: "Customer health report",
    defaultTitle: "Customer health report",
    description: "Outcomes, usage, stakeholder map, risks, opportunities, and mutual commitments.",
    outcome: "See the account as a relationship and outcome system, not a health score.",
    sections: [
      "Executive read",
      "Outcomes",
      "Usage",
      "Stakeholders",
      "Risks",
      "Opportunities",
      "Commitments",
    ],
    inputs: [
      input("Account", "Customer or partner", true),
      input("Evidence", "Notes, usage, and commitments", true),
      input("Period", "Review window"),
    ],
    tags: ["customer", "account", "report"],
  },
  {
    id: "market-landscape",
    kind: "artifact",
    category: "Report",
    format: "md",
    title: "Market landscape",
    defaultTitle: "Market landscape",
    description:
      "Category definition, forces, segments, players, comparison method, whitespace, and implications.",
    outcome: "Replace logo maps with a defensible view of how a market is moving.",
    sections: [
      "Category",
      "Forces",
      "Segments",
      "Players",
      "Comparison",
      "Whitespace",
      "Implications",
      "Sources",
    ],
    inputs: [
      input("Market", "The category being studied", true),
      input("Question", "What decision should this inform?"),
      input("Sources", "Research artifacts or links"),
    ],
    tags: ["market", "competitive", "report"],
  },
  {
    id: "project-hub",
    kind: "artifact",
    category: "Site",
    format: "html",
    title: "Project hub",
    defaultTitle: "Project hub",
    description:
      "A living front door for the brief, status, milestones, decisions, artifacts, and people.",
    outcome: "Give a project one understandable home without replacing its working tools.",
    sections: ["Brief", "Now", "Milestones", "Decisions", "Artifacts", "People", "Update history"],
    inputs: [
      input("Project", "Project name", true),
      input("Outcome", "What success changes"),
      input("Artifacts", "The work this hub should point to"),
    ],
    tags: ["project", "hub", "site"],
  },
  {
    id: "launch-page",
    kind: "artifact",
    category: "Site",
    format: "html",
    title: "Launch page",
    defaultTitle: "Launch page",
    description:
      "A focused single-page story with value, proof, product explanation, detail, and action.",
    outcome: "Make the value obvious before asking the visitor to understand the machinery.",
    sections: ["Value proposition", "Proof", "How it works", "Use cases", "Details", "Action"],
    inputs: [
      input("Offer", "What is available?", true),
      input("Audience", "Who should care?", true),
      input("Proof", "Evidence, quote, or result"),
    ],
    tags: ["launch", "marketing", "site"],
  },
  {
    id: "context-manifest",
    kind: "artifact",
    category: "Agent",
    format: "md",
    title: "Context manifest",
    defaultTitle: "Context manifest",
    description:
      "Purpose, sources, operating rules, tool expectations, publish behavior, and starter prompts.",
    outcome: "Make an agent setup understandable before it acts.",
    sections: [
      "Purpose",
      "What this context knows",
      "Operating rules",
      "Tools",
      "Publishing",
      "Boundaries",
      "Starter prompts",
    ],
    inputs: [
      input("Job", "What should this context make easier?", true),
      input("Sources", "What should it know?"),
      input("Boundaries", "What must it not do?"),
    ],
    tags: ["context", "agent", "manifest"],
  },
  {
    id: "skill-package",
    kind: "artifact",
    category: "Agent",
    format: "md",
    title: "Skill package",
    defaultTitle: "Skill package",
    description:
      "Trigger, inputs, procedure, safety boundaries, output contract, examples, and verification.",
    outcome: "Turn expert practice into a procedure an agent can use reliably.",
    sections: [
      "When to use",
      "Inputs",
      "Procedure",
      "Safety",
      "Output contract",
      "Examples",
      "Verification",
    ],
    inputs: [
      input("Capability", "What should the skill enable?", true),
      input("Triggers", "When should an agent reach for it?"),
      input("Examples", "Representative successful cases"),
    ],
    tags: ["skill", "agent", "procedure"],
  },
  {
    id: "review-rubric",
    kind: "artifact",
    category: "Agent",
    format: "md",
    title: "Review rubric",
    defaultTitle: "Review rubric",
    description:
      "Criteria, severity, evidence requirements, pass conditions, and a concise response format.",
    outcome: "Make automated and human review consistent without hiding judgment.",
    sections: [
      "Purpose",
      "Criteria",
      "Severity",
      "Evidence",
      "Pass conditions",
      "Response format",
      "Examples",
    ],
    inputs: [
      input("Subject", "What is being reviewed?", true),
      input("Standards", "Policies or examples to apply"),
      input("Audience", "Who receives the findings?"),
    ],
    tags: ["review", "quality", "agent"],
  },
  {
    id: "automation-brief",
    kind: "artifact",
    category: "Agent",
    format: "md",
    title: "Automation brief",
    defaultTitle: "Automation brief",
    description:
      "Trigger, instruction, sources, expected outputs, failure handling, approvals, and observability.",
    outcome: "Specify recurring agent work so its behavior can be reviewed before it runs.",
    sections: [
      "Outcome",
      "Trigger",
      "Instruction",
      "Sources",
      "Output",
      "Approvals",
      "Failure handling",
      "Observability",
    ],
    inputs: [
      input("Job", "What repeats?", true),
      input("Trigger", "When should it run?", true),
      input("Authority", "What may it publish or change?"),
    ],
    tags: ["automation", "agent", "operations"],
  },
  {
    id: "source-guide",
    kind: "artifact",
    category: "Agent",
    format: "md",
    title: "Source guide",
    defaultTitle: "Source guide",
    description:
      "What a connected system contains, preferred tools, query patterns, caveats, and citation rules.",
    outcome: "Help an agent use a source accurately without relearning its edges each session.",
    sections: [
      "Source",
      "What it contains",
      "Preferred tools",
      "Query patterns",
      "Caveats",
      "Citation rules",
      "Examples",
    ],
    inputs: [
      input("System", "The connected source", true),
      input("Tools", "Available operations"),
      input("Caveats", "Known gaps or permission boundaries"),
    ],
    tags: ["source", "agent", "guide"],
  },
]
