#!/usr/bin/env node
// Generates apps/api/src/skills-reference.gen.ts from apps/api/src/skills/*.md.
//
// The MCP CORE SKILLS are the workflow/protocol prose that used to live inline in every
// tool description. They live as real markdown files (frontmatter: name, summary, order;
// body = the skill) so they can be edited and previewed as markdown — no backtick-escaped
// template literals. This script inlines them into a generated .ts (bodies via
// JSON.stringify, so nothing needs escaping) that both the Node and Workers builds import.
//
//   node scripts/gen-skills.mjs           # write the generated file
//   node scripts/gen-skills.mjs --check   # fail if it is stale (CI)
import { readdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..")
const SKILLS_DIR = join(ROOT, "apps/api/src/skills")
const OUT = join(ROOT, "apps/api/src/skills-reference.gen.ts")

/** Split a `.md` with leading `---`…`---` frontmatter into {meta, body}. The body is kept
 *  verbatim (it may itself contain `---` horizontal rules — only the FIRST block is meta). */
const parse = (text) => {
  if (!text.startsWith("---\n")) throw new Error("missing frontmatter")
  const close = text.indexOf("\n---\n", 3)
  if (close === -1) throw new Error("unterminated frontmatter")
  const meta = {}
  for (const line of text.slice(4, close).split("\n")) {
    const i = line.indexOf(": ")
    if (i !== -1) meta[line.slice(0, i)] = line.slice(i + 2)
  }
  return { meta, body: text.slice(close + 5) }
}

const skills = readdirSync(SKILLS_DIR)
  .filter((f) => f.endsWith(".md"))
  .map((f) => {
    const { meta, body } = parse(readFileSync(join(SKILLS_DIR, f), "utf8"))
    if (!meta.name || !meta.summary || !meta.order)
      throw new Error(`${f}: frontmatter needs name, summary, order`)
    return { name: meta.name, summary: meta.summary, order: Number(meta.order), body }
  })
  .sort((a, b) => a.order - b.order)

const entries = skills
  .map(
    (s) =>
      `  {\n    name: ${JSON.stringify(s.name)},\n    summary: ${JSON.stringify(s.summary)},\n    body: ${JSON.stringify(s.body)},\n  },`,
  )
  .join("\n")

const content = `// GENERATED by scripts/gen-skills.mjs from apps/api/src/skills/*.md — do not edit.
// Regenerate: pnpm gen:skills
//
// The MCP core skills: workflow/protocol prose moved out of the always-loaded tool
// descriptions into lazily-read markdown (derive://skills/<name>, also via the read tool).
// A pure leaf: no imports, safe in every build (worker + node). Edit the .md sources.
export const CORE_SKILLS: readonly { name: string; summary: string; body: string }[] = [
${entries}
]
`

const args = process.argv.slice(2)
if (args.includes("--check")) {
  let current = ""
  try {
    current = readFileSync(OUT, "utf8")
  } catch {
    /* missing → stale */
  }
  if (current !== content) {
    console.error(
      "check-skills: apps/api/src/skills-reference.gen.ts is stale vs apps/api/src/skills/*.md.",
    )
    console.error("  Fix: pnpm gen:skills")
    process.exit(1)
  }
  console.log("check-skills: ok — the generated skills match the .md sources")
} else {
  writeFileSync(OUT, content)
  console.log(
    `gen-skills: wrote apps/api/src/skills-reference.gen.ts (${skills.length} skills: ${skills.map((s) => s.name).join(", ")})`,
  )
}
