import { expect, it } from "vitest"
import { anonApp } from "./helpers"

// The OpenAPI document is generated only from the contract-first routes (the ones using
// createRoute), and routers migrate one at a time — so a route absent from the spec is not
// by itself a bug. What IS a bug is that nothing noticed which routes were absent: the
// backend → spec link was the one unguarded step in a chain whose other two links (spec →
// web types, and the spec snapshot itself) are already machine-checked.
//
// This is a ratchet, not a coverage gate. The snapshot lists every mounted route the spec
// does not describe. Adding a route the old way appends a line; migrating a router removes
// lines. Either way the change is visible in review instead of silent, and the list only
// has one direction to go.
//
// Regenerate deliberately with `pnpm --filter @derive/api exec vitest run -u
// test/route-coverage.test.ts`, and expect the reviewer to ask why a line was added.

/** Hono records one entry per registered handler, including middleware. */
type HonoRoute = { method: string; path: string }

const HTTP_METHODS = new Set(["GET", "POST", "PUT", "PATCH", "DELETE"])

/** `{shortId}` (OpenAPI) and `:shortId` (Hono) name the same route. */
const canonical = (path: string) => path.replace(/\{(\w+)\}/g, ":$1").replace(/\/+$/, "") || "/"

const mountedRoutes = () => {
  const routes = (anonApp as unknown as { routes: HonoRoute[] }).routes
  const seen = new Set<string>()
  for (const { method, path } of routes) {
    // `ALL` entries are middleware, and a wildcard is a mount point rather than an endpoint.
    if (!HTTP_METHODS.has(method) || path.includes("*")) continue
    seen.add(`${method} ${canonical(path)}`)
  }
  return seen
}

const documentedRoutes = async () => {
  const res = await anonApp.request("/openapi.json")
  const spec = (await res.json()) as { paths: Record<string, Record<string, unknown>> }
  const seen = new Set<string>()
  for (const [path, operations] of Object.entries(spec.paths)) {
    for (const method of Object.keys(operations)) {
      if (HTTP_METHODS.has(method.toUpperCase())) {
        seen.add(`${method.toUpperCase()} ${canonical(path)}`)
      }
    }
  }
  return seen
}

it("locks the set of mounted routes the OpenAPI document does not describe", async () => {
  const mounted = mountedRoutes()
  const documented = await documentedRoutes()

  // Guards the extraction itself: if `routes` ever stops being populated, every route would
  // look documented and the ratchet would pass while checking nothing.
  expect(mounted.size).toBeGreaterThan(100)
  expect(documented.size).toBeGreaterThan(100)

  const undocumented = [...mounted].filter((route) => !documented.has(route)).sort()

  // The file sits next to openapi.json and is read by people, not just by this test, so it
  // carries its own header: openapi.json is what the spec covers, this is what it does not.
  const header = [
    "# Mounted routes that openapi.json does not describe.",
    "#",
    "# Generated by apps/api/test/route-coverage.test.ts. Do not edit by hand:",
    "#   pnpm --filter @derive/api exec vitest run -u test/route-coverage.test.ts",
    "#",
    "# This list should only ever get shorter. A route added without createRoute appends a",
    "# line here; migrating a router to createRoute removes lines. If your diff adds one,",
    "# that is the review question: does this endpoint belong in the public contract?",
    "",
  ]

  await expect(`${[...header, ...undocumented].join("\n")}\n`).toMatchFileSnapshot(
    "../undocumented-routes.txt",
  )
})
