// Emoji shortcodes for comments: `:tada:` renders as 🎉, and the composer's
// picker inserts the character directly. A curated common set (GitHub/Slack
// style) rather than a full dataset, so it stays a few KB and inside the bundle
// budget. Unknown shortcodes are left as literal text.

export const EMOJI: Record<string, string> = {
  // faces + people
  smile: "😄",
  grin: "😁",
  joy: "😂",
  rofl: "🤣",
  sweat_smile: "😅",
  wink: "😉",
  blush: "😊",
  slightly_smiling_face: "🙂",
  upside_down_face: "🙃",
  thinking: "🤔",
  neutral_face: "😐",
  expressionless: "😑",
  unamused: "😒",
  roll_eyes: "🙄",
  smirk: "😏",
  flushed: "😳",
  sob: "😭",
  cry: "😢",
  sweat: "😓",
  weary: "😩",
  tired_face: "😫",
  triumph: "😤",
  rage: "😡",
  angry: "😠",
  exploding_head: "🤯",
  sunglasses: "😎",
  nerd_face: "🤓",
  star_struck: "🤩",
  partying_face: "🥳",
  hugs: "🤗",
  shushing_face: "🤫",
  zipper_mouth_face: "🤐",
  grimacing: "😬",
  yawning_face: "🥱",
  sleeping: "😴",
  face_with_monocle: "🧐",
  raised_eyebrow: "🤨",
  pleading_face: "🥺",
  melting_face: "🫠",
  saluting_face: "🫡",
  // hands + gestures
  "+1": "👍",
  thumbsup: "👍",
  "-1": "👎",
  thumbsdown: "👎",
  ok_hand: "👌",
  pinched_fingers: "🤌",
  wave: "👋",
  raised_hands: "🙌",
  clap: "👏",
  pray: "🙏",
  handshake: "🤝",
  muscle: "💪",
  point_up: "☝️",
  point_right: "👉",
  point_left: "👈",
  point_down: "👇",
  crossed_fingers: "🤞",
  fist: "✊",
  punch: "👊",
  v: "✌️",
  metal: "🤘",
  call_me_hand: "🤙",
  writing_hand: "✍️",
  // hearts + symbols
  heart: "❤️",
  orange_heart: "🧡",
  yellow_heart: "💛",
  green_heart: "💚",
  blue_heart: "💙",
  purple_heart: "💜",
  black_heart: "🖤",
  white_heart: "🤍",
  broken_heart: "💔",
  sparkling_heart: "💖",
  heartpulse: "💗",
  fire: "🔥",
  sparkles: "✨",
  star: "⭐",
  star2: "🌟",
  zap: "⚡",
  boom: "💥",
  collision: "💥",
  dizzy: "💫",
  bulb: "💡",
  exclamation: "❗",
  question: "❓",
  warning: "⚠️",
  white_check_mark: "✅",
  heavy_check_mark: "✔️",
  x: "❌",
  no_entry: "⛔",
  recycle: "♻️",
  hourglass: "⏳",
  alarm_clock: "⏰",
  lock: "🔒",
  unlock: "🔓",
  key: "🔑",
  mag: "🔍",
  // celebration + objects
  tada: "🎉",
  confetti_ball: "🎊",
  balloon: "🎈",
  gift: "🎁",
  trophy: "🏆",
  medal: "🏅",
  "1st_place_medal": "🥇",
  dart: "🎯",
  rocket: "🚀",
  airplane: "✈️",
  hammer: "🔨",
  wrench: "🔧",
  gear: "⚙️",
  package: "📦",
  pushpin: "📌",
  paperclip: "📎",
  pencil: "✏️",
  memo: "📝",
  book: "📖",
  books: "📚",
  clipboard: "📋",
  chart_with_upwards_trend: "📈",
  chart_with_downwards_trend: "📉",
  bar_chart: "📊",
  calendar: "📅",
  email: "📧",
  bell: "🔔",
  loudspeaker: "📢",
  link: "🔗",
  computer: "💻",
  iphone: "📱",
  battery: "🔋",
  money_with_wings: "💸",
  moneybag: "💰",
  gem: "💎",
  bomb: "💣",
  shield: "🛡️",
  // food + drink
  coffee: "☕",
  tea: "🍵",
  beer: "🍺",
  beers: "🍻",
  champagne: "🍾",
  clinking_glasses: "🥂",
  pizza: "🍕",
  hamburger: "🍔",
  taco: "🌮",
  cake: "🍰",
  birthday: "🎂",
  cookie: "🍪",
  doughnut: "🍩",
  apple: "🍎",
  // nature + animals
  goat: "🐐",
  unicorn: "🦄",
  dog: "🐶",
  cat: "🐱",
  fox: "🦊",
  bear: "🐻",
  panda: "🐼",
  penguin: "🐧",
  snake: "🐍",
  whale: "🐳",
  dolphin: "🐬",
  butterfly: "🦋",
  bee: "🐝",
  bug: "🐛",
  turtle: "🐢",
  rainbow: "🌈",
  sunny: "☀️",
  cloud: "☁️",
  snowflake: "❄️",
  ocean: "🌊",
  earth_americas: "🌎",
  moon: "🌙",
  seedling: "🌱",
  herb: "🌿",
  four_leaf_clover: "🍀",
  rose: "🌹",
  sunflower: "🌻",
  // misc / status
  eyes: "👀",
  brain: "🧠",
  skull: "💀",
  ghost: "👻",
  alien: "👽",
  robot: "🤖",
  poop: "💩",
  wave_hand: "👋",
  "100": "💯",
  "+100": "💯",
  ship: "🚢",
  construction: "🚧",
  hot_pepper: "🌶️",
  snail: "🐌",
  turtle_slow: "🐢",
  zzz: "💤",
}

/** Replace `:shortcode:` tokens with their emoji. Unknown codes are left as-is.
 *  Operates on already-HTML-escaped text (the chars it inserts are safe). */
export const emojifyShortcodes = (s: string): string =>
  s.replace(/:([a-z0-9_+-]+):/gi, (whole, code: string) => EMOJI[code.toLowerCase()] ?? whole)

/** A compact, ordered set for the composer's quick picker (one tap to insert). */
export const PICKER_EMOJI: string[] = [
  "👍",
  "👎",
  "❤️",
  "🎉",
  "🔥",
  "🚀",
  "✨",
  "💯",
  "👀",
  "🙏",
  "👏",
  "🙌",
  "💪",
  "🤝",
  "😄",
  "😂",
  "😉",
  "😎",
  "🤔",
  "🤯",
  "🥳",
  "😅",
  "😬",
  "😢",
  "✅",
  "❌",
  "⚠️",
  "💡",
  "⭐",
  "💖",
  "🤖",
  "🐐",
  "☕",
  "🍕",
  "🎂",
  "💸",
  "📈",
  "📝",
  "🔗",
  "🐛",
]
